### ISSUE TITLE
Collecting restaurant menu prices

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/serenata-de-amor#102]
One of the hypothesis that we are planning to work on the next two months is about collecting and evaluating restaurant menu prices. We don't know where is the best place to collect these data, but we're thinking about collecting from Google Maps, Yelp or Foursquare.

Ideally we will use those data to return the probability of the hypothesis that a given expense is a suspcious outlier in its group.

**Comment by anaschwendler** [comment]
News: 
Restaurant prices changes everyday and we cannot count with the prices by now for a 2011 receipts, for example. So, talking with @cuducos and @Irio i was thinking in better ways to get the prices, and what passed in my mind is that we can use the data we already have from the receipts from CEAP to get an average cost for restaurants (thinking that there are more than one receipt for some restaurants).
By doing that we can already find some outliers, it's not the best way, but it's a start.

@cuducos suggested that we can use foursquare and google maps to check how expensive a restaurant is (by the rating that they have) and use that to match with the receipts we have from the restaurants and if it fits to what we got.

**Comment by thcavalcante** [comment]
Trip advisor is a good resource to find out the average too.

**Comment by talespaiva** [comment]
Hi, I took some advice from this thread to create the PR #129. Hope it's not duplicated work.

**Comment by rafaelcostadefarias** [comment]
Some prices can be collected at ifood. Maybe with a webcrawler?

**Comment by cuducos** [comment]
Hi @rafaelcostadefarias,

> Some prices can be collected at ifood. Maybe with a webcrawler?

IMHO this is not the best approach due to what @anaschwendler [has explained above](https://github.com/datasciencebr/serenata-de-amor/issues/102#issuecomment-259171939) — but thanks for the idea anyway ; )

**Comment by filipelinhares** [comment]
Hi guys. I'm working on a script to collect info from [Yelp](https://yelp.com).

**Comment by Irio** [comment]
@cuducos I believe @rafaelcostadefarias' idea is good even with @anaschwendler's proposal. The repo may accept multiple analysis in the same subject.

**Comment by cuducos** [comment]
@Irio: not sure if we're talking about new analysis (in my mind: new `.ipynb`) or new datasets (in my mind: new CSVs).

Anyway I would be extra cautious in taking iFood prices from today to ponder on 2011 data for examples (and that was my concern when it comes to @rafaelcostadefarias's suggestion) — so adding a new dataset might be harmful in that sense. Adding a new analysis notebook is fine though (because we can make explicit the limitations of the data from iFood).

**Comment by Irio** [comment]
@cuducos Past prices and their differences should also be considered in the analysis and in the possible model to come after. The data scientist could update prices using inflation functions, use just for comparison between restaurants (e.g. A has a greater price than B today, so in the past may have happened the same difference), compare iFood's dataset with Foursquare's and Yelp's or even use the dataset to analyze expenses of recent months. That's why I believe collecting iFood's prices could be useful for the project.

**Comment by cuducos** [comment]
@irio 🎤 ⬇️ 

I'm happy with your suggestion now @rafaelcostadefarias 👍

Soyry about the noise ; )

**Comment by rafaelcostadefarias** [comment]
I'm glad to help! @irio <https://github.com/irio> did a great job
explaining my idea better than me :)

**Comment by filipelinhares** [comment]
I tried to get data from **Trip Advisor** but they don't allow to use the API for data collection or research purposes.

/cc @thcavalcante.

**Comment by filipelinhares** [comment]
I'm working to scrap **IFood** data. If anyone has any sugestion, please let me know.

/cc @cuducos, @Irio, @rafaelcostadefarias

**Comment by rafaelcostadefarias** [comment]
Would it be unnecessary to contact iFood and ask if they have any API for
consultation or even if they could provide the data in .csv?

If not, I can try contacting their press office. I think it would be good
publicity for them and better data for the Serenata de Amor.

**Comment by vmesel** [comment]
@cuducos @Irio and @anaschwendler why we don't apply the monetary corrections to the prices that we have today to get an estimated price for the type of plate, drink, portion or restaurant?

**Comment by Irio** [comment]
@vmesel That would be recommended.

**Comment by MoizesMedes** [comment]
Could we use standard deviation? We would define a pattern of prices, the price with deviation above the standard is where we have to found the problem. That solution could serve in almost all metrics.

**Comment by mathiasmartens** [comment]
We can use IBGE census data from GIS files to cross a restaurant address (converted to lat long) with the census sector demographic info. (e.g average income). That makes a lot of sense if you agree that companies stay where they target customers really are (geo marketing stuff).
I thing is not a big deal to get those datasets in CSV.
This link (in portuguese) explains how to use QGIS with those data; http://urbanidades.arq.br/2015/06/mapas-de-densidade-populacional-com-dados-do-ibge-e-qgis/.

**Comment by cuducos** [comment]
Closed mainly due to other strategies adopted for meal outliers(PR #165) , but also due to some data collection (PR #146 and #148)
