### ISSUE TITLE
Collecting civil names of congressperson

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/serenata-de-amor#120]
In a talk with @wisner23 and @cuducos we discovered that we only have the congressperson name, not their civil names. Getting those names is relevant and important to our project, since we can by using those names, explore more datasets in a better way.

The idea is to create a dataset that associate civil name to congressperson name, using the data from [câmara](http://www2.camara.leg.br/deputados/liderancas-e-bancadas/bancadas/bancada-atual). Remembering that our congressperson_id matches with the id of congressperson of câmara website :)

**Comment by wisner23** [comment]
i'm try work on it

**Comment by Irio** [comment]
http://www2.camara.leg.br/transparencia/recursos-humanos/quadro-remuneratorio/consulta-deputados

**Comment by anaschwendler** [comment]
@Irio That link has only the actual congressperson elected. With that script we fetch all congressperson civil names, including from other elections.

**Comment by anaschwendler** [comment]
fix #120

**Comment by cuducos** [comment]
Fixed by #132

**Comment by anaschwendler** [comment]
@wisner23 thanks for you work again, it's on! :tada:

**Comment by wisner23** [comment]
I always I'll be helping ;P
