### ISSUE TITLE
Update CONTRIBUTING.md - Docker installation section

### ISSUE THREAD

**Issue by ivolima** [datasciencebr/serenata-de-amor#124]
In the **Docker Installation Environment** section, topic 2, you are asked to create a _config.ini_ file, with keys to AWS and Google. However, its function is not explained, making it appear that file creation is mandatory. We should refer to the section **Source files (src /)**, subsections **Suppliers information (CNPJ)** and **Miscellaneous**, where the use of the keys is explained.

**Comment by cuducos** [comment]
Thanks @ivolima — I'm testing a new branch that fixes that. If it works I'll send a PR in the newt few minutes ; )

**Comment by cuducos** [comment]
Closed by #271
