### ISSUE TITLE
Calculate and find anomalies on traveled speeds from last meal

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#13]
The Quota for Exercise of Parliamentary activity says that meal expenses can be reimbursed just for the politician, excluding guests and assistants. Creating a feature with information of traveled speed from last meal can help us detect anomalies compared to other expenses.

For doing so, we need the location of each expense. One possible way of getting that is fetching the address of each CNPJ receiving money from expenses with "Congressperson meal" as `subquota_description`.

**Comment by leportella** [comment]
I am trying to work on it

**Comment by anaschwendler** [comment]
@leportella by the way, great work! Can you tell us more of what you've done?
I think that the way now is finding the analysis about distances and time differentes.
