### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by fcevado** [datasciencebr/serenata-de-amor#131]
After reading the contribution guide, I'm with the impression that the organization of the repository structure is a little confusing.

I would like to suggest some changes:
Rather than having one big repository I think it would be more organized to have 3 or 4 repositories:
* one data-extraction repository
* one data-analysis repository
* one data repository(i think that given the nature of our data, it could become restrictive to get the data by re-processing it every time. it could even be an `sqlite` database file)
* this repository to centralize the reports generated.

**Comment by cuducos** [comment]
Hi @fcevado,

You suggestion is basically to split our [directory structure](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#best-practices) in repos: `/src` would become the data extraction repo, `/develop` would become the data analysis repo, `/data` the data repository and whatever is left was the centralizing one.

I see no gain in splitting them though. Like that basically with one `git clone` you're ready to get started. Anyway, as I'm not a specialist in data science maybe @Irio can add to this topic too.

**Comment by fcevado** [comment]
@cuducos it is possible to refer this other repos as [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and a simple `git clone --recursive` in this repository would bring them all.

**Comment by cuducos** [comment]
BTW, no step requires users to  _get the data by re-processing it every time_. `src/fetch_datasets.py` (ran by `setup`) download processed data from our servers. It's less than 50Mb of compressed CSV (`.xz`).

**Comment by fcevado** [comment]
> BTW, no step requires users to get the data by re-processing it every time. src/fetch_datasets.py (ran by setup) download processed data from our servers. It's less than 50Mb of compressed CSV (.xz).

It's my mistake. When I was reading the contributing guide i guess i misanderstood how the data folder works. Sorry =/
