### ISSUE TITLE
Inconsistent data when comparing the XML with Chamber of Deputies website

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#133]
Peeps,

Irio and I were exploring the dataset trying to understand diferences in `net_value` and we ended up finding some edge cases that pointed us to some very specific questions to raise to the Chamber of Deputies.

I just sent them a request for further information. The protocol is `3498103623673` and as soon as they reply I'll share here whatever I get from them.

---

Just in case, this was my message (if someone wanna investigate further):

> Boa tarde,
> 
> Estou estudando os documentos referentes à Cota para Exercício da Atividade Parlamentar e estou com duas dúvidas quanto aos dados divulgados por vocês.
>
> Especificamente minhas duas perguntas são:
>
> 1) O que significa a ausência do campo numRessarcimento nos arquivos em XML?
> 2) Existe alguma razão para os dados estarem no XML mas não no site da Câmara?
>
> Por exemplo podemos pegar a prestação de contas do Dep. Washington Reis para combustíveis e lubrificantes referente a julho de 2015. Buscando no site da Câmara chego a essa URL: http://www.camara.gov.br/cota-parlamentar/analitico?nuDeputadoId=2331&dataInicio=7/2015&dataFim=7/2015&despesa=3&nomeHospede=&nomePassageiro=&nomeFornecedor=&cnpjFornecedor=&numDocumento=&sguf=
> 
> Tal página me mostra apenas UMA ocorrência de reembolsos referentes a gastos na empresa portadora do CNPJ 09.036.204/0001-57. A mesma busca, no XML, me traz TRÊS ocorrências de reembolsos referentes a gastos na empresa portadora do mesmo CNPJ:
>
> Ocorrência I
>
> ideDocumento 5756825
> txNomeParlamentar WASHINGTON REIS
> ideCadastro 160620
> nuCarteiraParlamentar 326
> nuLegislatura 2015
> sgUF RJ
> sgPartido PMDB
> codLegislatura 55
> numSubCota 3
> txtDescricao COMBUSTÍVEIS E LUBRIFICANTES.
> numEspecificacaoSubCota 1
> txtDescricaoEspecificacao Veículos Automotores
> txtFornecedor AUTO POSTO PARADA CERTA UM LTDA
> txtCNPJCPF 09036204000157
> txtNumero 804
> indTipoDocumento 0
> datEmissao 2015-08-04 00:00:00
> vlrDocumento 3158.51
> vlrGlosa 0
> vlrLiquido 2508.88
> numMes 7
> numAno 2015
> numParcela 0
> txtPassageiro NaN
> txtTrecho NaN
> numLote 1215673
> numRessarcimento NaN
> vlrRestituicao NaN
> nuDeputadoId 2331
> 
> Ocorrência II
> 
> ideDocumento 5756825
> txNomeParlamentar WASHINGTON REIS
> ideCadastro 160620
> nuCarteiraParlamentar 326
> nuLegislatura 2015
> sgUF RJ
> sgPartido PMDB
> codLegislatura 55
> numSubCota 3
> txtDescricao COMBUSTÍVEIS E LUBRIFICANTES.
> numEspecificacaoSubCota 1
> txtDescricaoEspecificacao Veículos Automotores
> txtFornecedor AUTO POSTO PARADA CERTA UM LTDA
> txtCNPJCPF 09036204000157
> txtNumero 804
> indTipoDocumento 0
> datEmissao 2015-08-04 00:00:00
> vlrDocumento 3158.51
> vlrGlosa 0
> vlrLiquido 3158.51
> numMes 7
> numAno 2015
> numParcela 0
> txtPassageiro NaN
> txtTrecho NaN
> numLote 1215673
> numRessarcimento 5132
> vlrRestituicao NaN
> nuDeputadoId 2331
> 
> Ocorrência III
> 
> ideDocumento 5756825
> txNomeParlamentar WASHINGTON REIS
> ideCadastro 160620
> nuCarteiraParlamentar 326
> nuLegislatura 2015
> sgUF RJ
> sgPartido PMDB
> codLegislatura 55
> numSubCota 3
> txtDescricao COMBUSTÍVEIS E LUBRIFICANTES.
> numEspecificacaoSubCota 1
> txtDescricaoEspecificacao Veículos Automotores
> txtFornecedor AUTO POSTO PARADA CERTA UM LTDA
> txtCNPJCPF 09036204000157
> txtNumero 804
> indTipoDocumento 0
> datEmissao 2015-08-04 00:00:00
> vlrDocumento 3158.51
> vlrGlosa 0
> vlrLiquido 2508.88
> numMes 7
> numAno 2015
> numParcela 0
> txtPassageiro NaN
> txtTrecho NaN
> numLote 1215673
> numRessarcimento 5156
> vlrRestituicao NaN
> nuDeputadoId 2331
> 
> Dessas três ocorrências apenas uma (a primeira) não tem o campo numRessarcimento, e apenas uma (a segunda) aparece no site. O que justifica ambas as diferenças?
> 
> Vale ressaltar que encontro essas aparentes inconsistências em outros reembolsos também. Utilizei os casos acima apenas como exemplo mesmo.
> 
> Muito obrigado,

---

@Irio when you push the notebook, can you link it here?

**Comment by cuducos** [comment]
Just got a (very good) [response from them](https://dl.dropboxusercontent.com/u/1311043/181104_159155_28903_3498103623673.pdf).

**Comment by cuducos** [comment]
**TL;DR**

* Any reimbursement without `reimbursement_number` wasn't actually executed (canceled/denied)
* These canceled reimbursement are included in the XML but do **not** appear in the Chamber of Deputies website
* It's normal for a reimbursement claim to have multiple `reimbursement_number` (i.e. the same reimbursement claim appears more than once in our datasets with a different `reimbursement_number`) because reimbursement might be partial
* They admit that empty `reimbursement_number` leads to confusion and they plan to not include them in the XML anytime soon.
* The data Chamber of Deputies website appears shows aggregates multiple reimbursement (i.e. `reimbursement_number`) in the same view/page.

**Comment by Irio** [comment]
Conclusions: our analysis (https://github.com/datasciencebr/serenata-de-amor/pull/134) gave the right results. Would have saved some time knowing this beforehand but in the end we did everything correctly.

![image](https://cloud.githubusercontent.com/assets/667753/20635231/92b4abda-b341-11e6-898c-536fe41d3228.png)
