### ISSUE TITLE
Data Source: chamber of deputies sessions/reunions webservice

### ISSUE THREAD

**Issue by fcevado** [datasciencebr/serenata-de-amor#137]
One of the webservices of open access from the chamber of deputies is [SessoesReunioes](http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/sessoesreunioes-2)(SessionReunions).

I was thinking to cross this data with expenditures and trace impossible expenses by matter of location(being in a session would result in being unable to expend on other states/countries). I talked about it on the telegram group and was raised some concerns about the the validity of this assumption.

Regardless this assumption, I wonder how useful would be to have this dataset disposable for further assumptions. I didn't read all the legislation bout this matter so I'm creating this issue to see if there is any concern bout the validity of this data.

**Comment by pmargreff** [comment]
You can use [this](https://github.com/vitorbaptista/dados-abertos-camara.gov.br) to generate the static files if it's necessary.

**Comment by fcevado** [comment]
@pmargreff this repo works on the webservice for [Proposicoes](http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1)(Propositions) and i'm talking about the _SessionsReunions_, they are a little different in content.
But right now i don't even worry bout implementation, I wanted to discuss about the validity of the data. I don't know, maybe there are legal ways to be remotely present on a session or reunion, or the expenditure was on behalf of the congressperson but who made it was an advisor or something like that. I think more important is to evaluate the data and if there are some space for doubt in an analysis with this data.

**Comment by Irio** [comment]
This data source can relate to https://github.com/datasciencebr/serenata-de-amor/issues/13: if we know the congressperson is in Brasília, it's impossible to eat a meal in Manaus 30 minutes after.

Good suggestion, @fcevado.

**Comment by fgrehm** [comment]
Hey guys, I did some hacking on this morning and wrote my first ever notebook 🐣 😄 https://gist.github.com/fgrehm/53fbc5a1d07e9b5cff01eac47d5dd186 TL;DR is that there are a couple endpoints that are not working as I expected but one of them is able to tell us the **date and time** that a congressperson did a speech 🤘

My python / jupyter skillz are not that great so any type of feedback would be great. Next steps for me would to do some reading on how to clean up and extract interesting stuff from that dataset

PS: Please note that the iframes do not seem to load on github so u gotta run it locally for a better experience

**Comment by cuducos** [comment]
From your notebook:

> Yes, we can identify deputies that were in Brasília in a given date and hour :)

This is a very very very first notebook, mate!… By cross checking these dates with some reimbursement `issue_date` from meals, for example,  I guess I could find _very interesting_ stuff if you know what I mean…

Weel done 🎉

**Comment by cuducos** [comment]
BTW… would you mind if I ask you what's next for you, not for the notebook? You could do a PR to [serenata-toolbox](https://github.com/datasciencebr/serenata-toolbox) adding a script to consolidate this dataset you created in our `data/` ; )

**Comment by fgrehm** [comment]
Cool! Here's a start https://github.com/datasciencebr/serenata-toolbox/compare/master...fgrehm:fetch-speeches-script, LMK if that's enough to kick off some discussions on a PR or not 🤘

**Comment by cuducos** [comment]
@fgrehm I have just minor comments. You can open a PR and we discuss the in a code review. Or I can send a PR to you fork — whatever works better for you ; )

**Comment by fgrehm** [comment]
Hey guys, I just found out that the `ListarPresencasParlamentar` (ListPresencesCongressperson) is working, example [here](http://www.camara.leg.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasParlamentar?dataIni=13/09/2016&dataFim=17/09/2016&numMatriculaParlamentar=491).

So `ListarPresencasParlamentar`, `ListarDiscursosPlenario` and possibly the "voting results" data available [here](http://www2.camara.leg.br/atividade-legislativa/plenario/resultadoVotacao) (just found out about this dataset yesterday, description about the data [here](http://www.camara.leg.br/internet/plenario/result/votacao/Layout_ArquivosTXT_presencas_vota%C3%A7%C3%A3o_exportados.pdf)) should give us a really good idea of when deputies are in Brasilia 💭

**Comment by fgrehm** [comment]
Quick update: Looks like Santa Claus is coming, I was able to scrape more data from those `SessoesReunioes` endpoints and more suspect reimbursements are coming. Just need to find the time to polish up the scripts I put together, looks like there more weird stuff going on 🎅
