### ISSUE TITLE
Use serenata_toolbox whenever possible

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#143]
https://github.com/datasciencebr/serenata-toolbox was created to keep code shared between different Serenata de Amor projects. If the script is already there, the code should be removed from here and used from the package.

**Comment by vmesel** [comment]
I think we should add this to the README file so we can ask people to use it, letting it on an issue is not so accessible as it must be.

**Comment by cuducos** [comment]
Almost agree, but CONTRIBUTING.md is where this info is gonna be added IMHO

**Comment by fgrehm** [comment]
I was willing to give this a shot but it seems that the package [is not on pypi yet](https://pypi.python.org/pypi/serenata_toolbox/), any recommendations on how to leverage that here? (git submodules, `wget`, something else...)

**Comment by cuducos** [comment]
We can install directly from GitHub [with the -e argument](
https://github.com/datasciencebr/rosie/blob/master/requirements.txt) ; )

**Comment by anaschwendler** [comment]
Talking with @Irio what's missing:
- Add the serenata-toolbox to requirements.txt
- We need to use serenata-toolbox in the notebooks

@jtemporal

**Comment by jtemporal** [comment]
feedback:
- [x] Add the serenata-toolbox to requirements.txt
- [x] Make sure that serenata toolbox works on the notebooks
- [ ] Remove from src all code that is already in the toolbox
- [ ] Check/Update documentation
