### ISSUE TITLE
Measuring restaurant prices with "$" quantity in social networks

### ISSUE THREAD

**Issue by vmesel** [datasciencebr/serenata-de-amor#154]
Is there any formula to define a restaurant mean price with the "$" quantity it has on certain projects like 4Square, Yelp, Trip Advisor and others? Is there any medium price for each of the "$" symbol defined somewhere in the net?

With the values we should be able to define a z-score value to define which activity should be considered suspicious.

**Comment by cuducos** [comment]
I think that this is full of nuances: a very cheap coffee (that means, only
one $ out of, say… five) means R$ 2 (just guessing, while a very cheap
"rodízio") would be 20x more (at least)…

**Comment by vmesel** [comment]
But then we should detect the type of location the guy was on

**Comment by cuducos** [comment]
Actually, the type of expense (one could stop by a bistro and have just a
coffee, for example)…

**Comment by vmesel** [comment]
That's really a big problem.

**Comment by vmesel** [comment]
@Irio and I were talking about our dataset and we discovered that we could do a mean of all the restaurants of a same category and discover the mean value of a meal, so we could establish a metric for new restaurants added in the dataset and for new invoices coming from restaurants of that kind.

**Comment by abmpicoli** [comment]
I've just taken a look at the Trip Advisor, and it seems that meal prices depends on what the individual evaluator consider cheap, average or expensive. An european tourist could classify our meals cheap, probably... Not mattering the restaurant. Also notice that what cheap or expensive is depends wholly on where the people are. R$20,00 is a cheap meal at São Paulo, but it would probably be a ripoff on some States.
In short, I don't consider the evaluation from travelling sites a good approach for evaluating this kind of abuse.
But I think we could use simple statistics here... if the congressman is abusing on their meal quota, this would show as an abnormally high value on that account. We could also identify the abnormally low values: they could be reference values: that is, an honest congressmen is taking an honest meal. 
Another point to note is that if there is some sort of embezzlement here, the restaurant would provide consistently cold bills with high values, possibly for other congressmen. So a cross-reference between the two data sources (restaurants x bills)  would show suspicious activity, worth concrete investigation.

**Comment by cuducos** [comment]
@abmpicoli Actually what you described is our first option, [implemented here](https://github.com/datasciencebr/rosie/blob/master/rosie/meal_price_outlier_classifier.py). This issue might give us an alternative dataset for further analysis though.

**Comment by abmpicoli** [comment]
I'm curious, do you have a concrete result of that specific analysis somewhere?
If there is a big group somewhere, nothing beats actual measure: maybe have volunteer crews actually showing concrete numbers of how much a meal costs at the most suspicious providers? Maybe a mobile app for feeding this sort of data?

**Comment by cuducos** [comment]
As we have already datasets from Foursquare and Yelp, I'm closing this issue — but we can chat, @abmpicoli, drop a line at our Telegram group or just keep posting here ; )

**Comment by cuducos** [comment]
> I'm curious, do you have a concrete result of that specific analysis somewhere?

Sure thing ; )

Just run [Rosie](https://github.com/datasciencebr/rosie) or take a look in @Irio's [notebook that inspired the classifier](https://github.com/datasciencebr/serenata-de-amor/blob/master/develop/2016-12-01-irio-anomalies-in-meal-prices.ipynb).

cc @abmpicoli
