### ISSUE TITLE
Error loading the Reimbursements dataset

### ISSUE THREAD

**Issue by vmesel** [datasciencebr/serenata-de-amor#159]
If you are on Windows and you are having problem loading the reimbursements.xz file on Pandas having the following output , maybe you will need to activate a parameter on pd.read_csv so you will be able to load.

## Error message:

```
pandas\parser.pyx in pandas.parser.TextReader.read (pandas\parser.c:8643)()

pandas\parser.pyx in pandas.parser.TextReader._read_rows (pandas\parser.c:9772)()

pandas\parser.pyx in pandas.parser.raise_parser_error (pandas\parser.c:23295)()

CParserError: Error tokenizing data. C error: out of memory
```

## Code
```python
import pandas as pd
import numpy as np

reimbursements = pd.read_csv('../data/2016-11-19-reimbursements.xz')
```

You may change to this

## Corrected code

```
import pandas as pd
import numpy as np

reimbursements = pd.read_csv('../data/2016-11-19-reimbursements.xz',
                                   dtype={'cnpj_cpf': np.str,
                                   'reimbursement_numbers': np.str},
                                   )
```

**Comment by cuducos** [comment]
Thanks for documenting this but I'm inclined to remove the Windows part of the issue title.

First of all the error does not seam to be related to the OS, but to memory handling when trying to guess the data type and to allocate data in memory.

Second treating `cnpj_cpf` and `reimbursement_numbers` explicitly as strings is more a best practice than an issue fix IMHO.

If you're OK with that we can reword the issue title and archive that in case more users end up with the same error message ; )

**Comment by vmesel** [comment]
@cuducos I'm ok with that man! Thanks for complementing my explaining!
