### ISSUE TITLE
Update CONTRIBUTING.md adding Rosie and the toolbox

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#162]
Our contribution guide needs to be updated to address [Rosie](https://github.com/datasciencebr/rosie) and the [`serenata-toolbox`](https://github.com/datasciencebr/serenata-toolbox). The content was basically discussed in [this Hangouts (pt-BR)]( https://t.co/ohFEfWc27d) earlier this week. Is any one willing to draft something in a PR?

**Comment by Irio** [comment]
I started drafting an article about this subject.

**Comment by cuducos** [comment]
> I started drafting an article about this subject.

It's [published](https://datasciencebr.com/how-does-one-contribute-to-serenata-de-amor-operation-36e3e7b38207) — now we have to update this issue: we're meant to emphasize it in the `CONTRIBUTING.md` instead ; )

**Comment by cuducos** [comment]
Closed by #183
