### ISSUE TITLE
RFC: New dataset - Official Missions to other countries

### ISSUE THREAD

**Issue by fgrehm** [datasciencebr/serenata-de-amor#175]
http://www.camara.leg.br/missao-oficial can give us a period of time when deputies are supposed to be out of the country ([example](http://www.camara.leg.br/missao-oficial/missao-pesquisa?deputado=1&nome-deputado=JUTAHY+JUNIOR&nome-servidor=&dati=01%2F01%2F2015&datf=04%2F01%2F2017&nome-evento=))

Much like the speeches and presence on sessions dataset I recently worked on, we can cross this information with reimbursements in Brazil that requires the deputy to be physically present. Might also check if an international flight ticket was issued for a period that the congressperson was NOT in a mission (maybe bought for "vacations"? who knows 🤔  )

**Comment by MaiaVinicius** [comment]
I'm on it. Collected all data, now is just store this at /data for analyze
Some sample of how is the last result:
`{'deputy': 'ALFREDO SIRKIS', 'data': {'start_date': '2011-10-14', 'end_date': '2011-10-30', 'subject': 'Cúpula Mundial sobre Baixo Carbono.', 'destination': 'Dalian, CHINA, CHINA', 'details': {'type_of_passage': 'Classe Executiva', 'unit_price': 'R$630', 'amount': '5'}}}`

**Comment by fgrehm** [comment]
Close by the toolbox PR above
