### ISSUE TITLE
Expose data using GraphQL

### ISSUE THREAD

**Issue by sibelius** [datasciencebr/serenata-de-amor#177]
Tks for this work!

I'm not sure if this is the best place to discuss this, but I think [GraphQL](http://graphql.org/) would be great to help people explore all this data.

I think the ideal workflow for this project would be:

- fetch data from sources from government
- store this data in a database (I think mongodb could be great for this)
- apply machine learning / data analysis on top of this data

I want to also expose this data though GraphQL so it could be easily used by other projects

[create-graphql](https://github.com/lucasbento/create-graphql) could be very helpful to create the graphql schema on top of the mongo database

**Comment by cuducos** [comment]
Not exactly related, but might be of interest: #101

**Comment by cuducos** [comment]
Yet some minor comments:

> I'm not sure if this is the best place to discuss this, but I think GraphQL would be great to help people explore all this data.

Sure this is the right place ; )

> store this data in a database (I think mongodb could be great for this)

We tend to store data as dataset files, not database — it's a best practice in data science. Works better in terms of reproducibility (versioning of datasets, for example: an analysis made with a data collect today will differ from an analysis with data collected a couple of weeks ago, but both must be reproducible by anyone). We tend to use the CSV format, which is better for tabular data, but in this case creating JSON files would work better — and surely would not be a problem in terms of best practices ; )

**Comment by ThaisFaria** [comment]
@sibelius Neo4j is a great tool for Graph queries since it models data as graphs on the DB instead of applying a layer of graphs on top of complicated queries and database performance. If you're looking to work with stored data + graphs, it might be worth to take a look. :)

**Comment by cuducos** [comment]
As this is quite similar to #101, and #101 is closed, I think I can archive this too.
