### ISSUE TITLE
Create Congressperson Type In Order to Include Municipal Councilor Data

### ISSUE THREAD

**Issue by guilhermemoschen** [datasciencebr/serenata-de-amor#180]
Hello There

I just discovered this project and, so far, it's a great initiative.

Just wonder about the scope about of congressperson, do you ever think about expand this?
I mean, create a kind of Congressperson Type in your DataSet and with this allow us to generate data about municipal councilor ("vereador"), for example.
Also, it could be good to configure the quota about the data analysis and other settings in order to help Rosie in her processing.

I'm from Curitiba and could create a robot (or something) which could generate a xml file with all municipal data in your format and request to be processed.

What do you think?

**Comment by cabral** [comment]
Hi @guilhermemoschen ! 
Expanding are on our roadmaps. Hence we need to find a way to keep us full-time at the project, but it's another subject. 

I think that you have a great idea and the I'll wait for Curitiba's XML. 
We need to understand what kind of data each municipality have and can deliver to fight corruption on the local level - we already start talking with ONGs and Public Ministery that will help with pressure on the transparency.

**Comment by cuducos** [comment]
Closed by inactivity — anyone feel free to re-open when needed
