### ISSUE TITLE
New data about companies

### ISSUE THREAD

**Issue by allantorres** [datasciencebr/serenata-de-amor#189]
I was searching about CNPJ APIs and i found a great beta API from Compras.dados.gov.br... 

http://compras.dados.gov.br/fornecedores/doc/fornecedor_pj/01645738000179

http://compras.dados.gov.br/fornecedores/doc/fornecedor_pj/01645738000179.json

This API show all information about the company and the contracts they have with the governament.

**Comment by Irio** [comment]
Great finding @allantorres.

**Comment by anapaulagomes** [comment]
I made a PR (#193) related to supplier's data collection. I wish contribute with some analysis related with the purchases and materials.

**Comment by caduvieira** [comment]
We could use https://www.receitaws.com.br/ also. There is available a free API there.

**Comment by cuducos** [comment]
> We could use https://www.receitaws.com.br/ also. There is available a free API there.

Why?

ReceitaWS has information about the company — [which we're already collecting](https://github.com/datasciencebr/serenata-de-amor/blob/19f7b603e0b396b1be27f62c901849c481d83cd4/src/fetch_cnpj_info.py#L71), but nothing on the contracts they have with the governament — so @allantorres's suggestion still has a strong point over ReceitaWS.

However, as mentioned #16 recently _now_ Receita WS is *also* publishing the partners of each company. It's a very very interesting to include in [`src/fetch_cnpj_info.py`](https://github.com/datasciencebr/serenata-de-amor/blob/19f7b603e0b396b1be27f62c901849c481d83cd4/src/fetch_cnpj_info.py#L71) ; )

**Comment by caduvieira** [comment]
Oh ok. I got it now. There is another API in siconv for data of public money transfers. Some company could be of some congressperson parent. http://dados.gov.br/dataset/siconv

**Comment by cuducos** [comment]
Closed by #193
