### ISSUE TITLE
Make setup running more friendly for users using Windows

### ISSUE THREAD

**Issue by vmesel** [datasciencebr/serenata-de-amor#209]
@rodolfo-viana asked me help to install serenata's code on his computer which is running Windows, and a suggestion came up:
We need to update the README.md file in the part that the user needs to run setup, instead of just saying "run setup" we should ask if the user is running windows, then he needs to run "python setup"

**Comment by jtemporal** [comment]
Actually we need to change the CONTRIBUTING.md it is a pretty easy fix by the way ;)
@vmesel would you like to do it?

**Comment by vmesel** [comment]
@jtemporal no time to it right now! could u do this for Rodolfo?

**Comment by jtemporal** [comment]
@vmesel Rodolfo was already setup when you opened the issue dude... And I know this because I helped him ;)
If other people have problems with setting up the windows environment ping me over telegram while the documentation is not properly set :)

**Comment by vmesel** [comment]
Dope bro!

**Comment by vmesel** [comment]
So I should close the issue and wait til another user to report the same thing?

**Comment by cuducos** [comment]
Please, leave the issue open: if anyone else would like to help, the open issue show them some possibilities ; )

**Comment by alexsandro-xpt** [comment]
Hello all, can I run Serenata de Amor in Docker Container?

**Comment by cuducos** [comment]
> Hello all, can I run Serenata de Amor in Docker Container?

[Sure thing](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#docker-installation-environment) ; )

**Comment by cuducos** [comment]
@vmesel and @jtemporal: can you briefly share what are the pain points in the install process in a Windows machine?

**Comment by jtemporal** [comment]
AFAIK
- run setup: in windows you have to run `python setup` instead of `./setup`
I believe that's mainly it ;)

**Comment by cuducos** [comment]
Is 5d3727e enough?

**Comment by vmesel** [comment]
@cuducos for better info, talk to @rodolfo-viana. He probably know better than me!

**Comment by rodolfo-viana** [comment]
I had some hard time installing the code. @vmesel and @jtemporal helped me and now it works fine. (Many thanks, folks!) 

I believe it would be helpful to other Windows users if CONTRIBUTING.md had some references related to Mucrosoft OS. 

For instance:
1. it is python setup, not ./setup.
2. it is activate serenata_de_amor, not source activate serenata_de_amor. 

But I really believe these issues are related to my "noobness" working with Python, and not any information gap in instructions.

**Comment by vmesel** [comment]
@rodolfo-viana nope, this kind of issues need to be repaired, because this is a repo made for every contributor (from beginners to advanced Python users). And this issue isn't exclusive on your computer or noobness, this issue is a documentation issue!

**Comment by jtemporal** [comment]
@rodolfo-viana as @vmesel said, this is a documentation issue, and we try to keep our documentation as friendly as possible for all independently of python expertise level.

@cuducos as pointed out by @rodolfo-viana 
we also need:
>activate serenata_de_amor, not source activate serenata_de_amor

pretty easy fix :)

**Comment by jtemporal** [comment]
Hey @rodolfo-viana if you have anymore things to point out due to your windows experience that would be much welcome ;)

**Comment by cuducos** [comment]
Is #211 enough?
