### ISSUE TITLE
Get social contract from Registro Livre

### ISSUE THREAD

**Issue by Lrcezimbra** [datasciencebr/serenata-de-amor#21]
There is a project [Registro Livre](http://registrolivre.inf.br/) which is [open source](https://github.com/ThoughtWorksInc/registrolivre) that the idea is to provide the social contracts of companies that are available at the _Junta Comercial_. We could use these data to cross business partners or other informations.

**Comment by Irio** [comment]
Hi @Lrcezimbra, thanks for your contribution. This is my first contact with the given project, and I can just see [10 companies listed in their site](http://registrolivre.inf.br/#/empresas). Do you know if they have more than that? If they just have this amount and don't plan to get information about more companies in the soon future, I find hard to understand how to connect both projects.

**Comment by Lrcezimbra** [comment]
I think they intend to add more companies, but I'm not sure how the project is flowing. I had the idea to use this project because the Receita Federal and ReceitaWS I think don't have the data from the partners. So that would be an option if more companies are added.

**Comment by pedrro** [comment]
Hi @Lrcezimbra @Irio I am a developer that worked on that project, maybe I can help with the contact of teacher that idealize this project.

The data that actually have there is true data, but was only added there to some usability tests. The intention is for this year the schoolchildren's will start to add more data there.

Feel free to contact me anytime

**Comment by caduvieira** [comment]
Refers to https://github.com/datasciencebr/serenata-de-amor/issues/42#issuecomment-246142151

**Comment by cabral** [comment]
Teacher reached. Scheduling phase.

**Comment by Irio** [comment]
Any updates on this, @cabral?

**Comment by cuducos** [comment]
Follow up:

@cabral just told me that the he recommended scrapping http://www.consultasocio.com

**Comment by wisner23** [comment]
I'm trying to work on it

**Comment by cuducos** [comment]
Now our source to get Federal Revenue data [offers this data](https://github.com/datasciencebr/serenata-de-amor/issues/16#issuecomment-286167555), so I'm closing this issue ‚ it's a matter of adapting one of our existing scripts and discussing it on #16
