### ISSUE TITLE
Comparing two or more congresspeople

### ISSUE THREAD

**Issue by valessiobrito** [datasciencebr/serenata-de-amor#210]
Pessoal,

Inspirado no projeto Diferentona ( https://github.com/luizaugustomm/diferentonas-client )

Seria possível ter alguma interface para comparar diferenças de gastos entre um gabinete de Deputado vs outro qualquer?  Ou todos de um determinado estado;

Enfim, acho que manualmente, comparando o Deputado X do partido Y do estado BA,   vs  outro deputado do mesmo estado de diferente partido;    E depois com outro estado,  poderia apresentar a lista dos "diferentões"; 

O Deputado(a) diferentão que gasta mais verba de Telefone ou Viagens no mesmo estado;  
A Deputada(o) diferentona que gasta mais verba de Refeição no mesmo estado;

etc.

**Comment by cuducos** [comment]
_[As the official language in English here, I'm just freely translating @valessiobrito's post]_

Folks,

Inspired by [Diferentona](https://github.com/luizaugustomm/diferentonas-client ) project:

Would it be possible to have an interface to compare expenses between one congressperson's office and another? Or all from a given state;

Well I think that manually comparing Congressperson X from party Y from BA state, vs. another congressperson from the same state and another party; And next against another state, that could present us the “big differences” (_diferentões_ in Portuguese).

Congressperson _diferentão_ who spends more on telephone or trips in the same state;
Congressperson _diferentão_ who spends more in meals from the same state.

**Comment by cuducos** [comment]
Hi @valessiobrito,

Actually there are to things that crossed my mind while reading your post:

1. We have little interest in analyzing stuff by state but mainly by party. Sometimes analyzing by state makes sense — e.g. when pondering expenses with flight tickets (it's reasonable to expect that congresspeople from RS expends more on flight tickets than congresspeople from GO), but definitively not by party. Our focus is on politicians themselves (and in spite of that they change parties all the time).

2. AFAIK the analysis you suggested is actually a byproduct of other analysis we already have (there are a couple of thematic notebooks on meals and transport for example that mention data like that). But the thing is that those thematic notebooks are more straightforward in suggesting a concrete hypothesis to be tested (in the notebook), ported as a classifier to Rosie and ending up as data to support official reports (i.e. to officially report improper use of public money to the authorities). This is what we have in mind in terms of _using machine learning for social control of public expenses_. Your suggestion IMHO tends to favor a more human (less automated) analysis of data — which is good, but is not the focus of the project (again IMHO).

Anyway you or anyone else is welcomed to write your own notebooks with these comparisons and open a PR. Nothing against that ; )

**Comment by cabral** [comment]
Noting the ultimate goal of the project, it makes no sense at this point a comparison between congressperson.
Obviously there is value in visualizing the data of deputies in every way, and it is often observed ranking of spending, but always against the entire collection of data and not against individuals. This choice reflects the option of not nurturing political dispute, but rather pointing to misuse of public funds.
