### ISSUE TITLE
Use new dataset manager module to upload data to S3

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#213]
**If [PR #38 from the `serenata-toolbox`](https://github.com/datasciencebr/serenata-toolbox/pull/38) is merged** we can cleanup this repo using `boto3` instead of `tinys3`. The main reson why is:

>  `tinys3` uses `requests` under the hood and [`requests` is unable to upload large files to S3 (more than 10MB)](https://github.com/kennethreitz/requests/issues/2422).

**Comment by vitorkusiaki** [comment]
@cuducos isn't it resolved by https://github.com/datasciencebr/serenata-toolbox/commit/a0e3c005a0cdaea6ce4bcaf3518b81bc71a8d62f ? Can this issue be closed?
