### ISSUE TITLE
Update companies dataset

### ISSUE THREAD

**Issue by fgrehm** [datasciencebr/serenata-de-amor#214]
Hey guys, the companies dataset is nearly 6 months old now and I've noticed that recent meal reimbursements include lots of new companies that can't be matched (something like 56901 meals out of 61757)

Would it be possible to release a new version of the CSV? Thanks in advance!

**Comment by jtemporal** [comment]
Hey @fgrehm working on it ;)

**Comment by cuducos** [comment]
Yep, @jtemporal and I were already worried about that when @marcusrehm noticed ReceitaWS was publishing the partner list of the companies (something that wasn't there when we first wrote the script). Once this is done we'll have a new dataset ; ) BTW discussion about that in #16

**Comment by fgrehm** [comment]
FYI - just tried matching the new dataset with meal reimbursements but it seems that we have less matches than the first dataset 😢 Something like 45422 reimbursements were matched by cnpj with the new dataset vs 56901 with the old one 🤷‍♂️

If that's not expected, LMK and I can provide a simple notebook explaining this

**Comment by marcusrehm** [comment]
@fgrehm could you please send some cnpjs as examples? Which reimbursement file are you using? Maybe we need to run the script passing it also.

I can run it again if I missed some source file. No problem! :smile:

**Comment by marcusrehm** [comment]
I'm running the script again for the 2017-03-15-reimnursement.xz dataset to add the missing cnpjs. When it finish I can post the file again ok?

**Comment by cuducos** [comment]
> we have less matches than the first dataset

Yep. It's a [kwon issue](https://github.com/datasciencebr/serenata-de-amor/issues/16#issuecomment-300774828) but we still haven't found why…

**Comment by marcusrehm** [comment]
Guys, I ran the script again adding 2017-03-05-reimbursement and now the companies.xz has 80.613 cnpjs.

You can download the file here [https://we.tl/mQUSgWNqzB](https://we.tl/mQUSgWNqzB)

/cc @fgrehm @cuducos @jtemporal

**Comment by marcusrehm** [comment]
I did some improvements in the fetch_cnpj_info to handle requests failed. I noticed that during the for loop some of the futures with errors were not getting reinserted in the loop maybe because of [this](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed):
> Any futures given by fs that are duplicated will be returned once.

So I created a outer loop which runs until there is no more cnpjs left to fetch.

I created the PR  #242.

/cc @cuducos @jtemporal

**Comment by cuducos** [comment]
Wow! Many thanks, @marcusrehm — I'll try to set them up today in S3 and toolbox.

**Comment by cuducos** [comment]
Closed by #242

**Comment by fgrehm** [comment]
FYI - with the new dataset I'm able to match on 61428 companies out of 61757 with meal reimbursements since 2015 (which I consider to be pretty much an 100% match) 🎉 🍻 tks a lot guys!
