### ISSUE TITLE
Add guppy to requirements.txt

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-de-amor#216]
`src/geocode_addresses.py` needs the `geopy` package which is not yet in the _requirements.txt_ and needs to be there.

geopy==1.11.0

**Comment by cuducos** [comment]
No need for that: [it's already in `conda_requirements.txt`](https://github.com/datasciencebr/serenata-de-amor/blob/master/conda_requirements.txt#L2) ; )

Maybe try a `conda install --yes --file conda_requirements.txt`…
