### ISSUE TITLE
Getting list of assistants' names

### ISSUE THREAD

**Issue by rodolfo-viana** [datasciencebr/serenata-de-amor#233]
Considering congressmen's assistants may use quota for some objetives (e.g. buying flight tickets), it would be great to have a list of their names for future analysis. 

For instance, it would allow us check whether the name on the plane ticket belongs to a congressperson or an assistant. If the name on the ticket does not match the congressperson's or one of the assistants', it indicates a possible irregularity. 

(There was a recent scandal dubbed "farra das passagens", in which congresspersons would buy tickets for their relatives and friends and get reimbursements from quota. [Further info here](http://congressoemfoco.uol.com.br/category/noticias/memoria/a-farra-das-passagens/).)

Would you agree this list would be a good asset to Serenata de Amor?

The point is how to get this list. As far as I know there is no `.csv` file containing the assistants' names, and the search on Deputies Chamber website sorts the list by the congressperson's name. Here: [http://www2.camara.leg.br/transparencia/recursos-humanos/servidores/lotacao/consulta-secretarios-parlamentares](http://www2.camara.leg.br/transparencia/recursos-humanos/servidores/lotacao/consulta-secretarios-parlamentares).

Suggestions on how to get a `.csv` file out of this? Is scrapping congressperson by congressperson the only way?

**Comment by cuducos** [comment]
Duplicates #139
