### ISSUE TITLE
Inconsistencies between suspicions?

### ISSUE THREAD

**Issue by vncscoelho** [datasciencebr/serenata-de-amor#251]
[This reimbursement from 02/2017](https://jarbas.serenatadeamor.org/#/documentId/6218730/) was considered suspected, but [this similar reimbursement ](https://jarbas.serenatadeamor.org/#/documentId/6198401/) from the previous month wasn't. It's normal behaviour?

**Comment by jtemporal** [comment]
Hi @vncscoelho the suspicion is based on gas sub quota which is 6000 reais per month.
>This reimbursement from 02/2017 was considered suspected

Probably, what happened is that in February the amount of reimbursements for that sub quota added up to more than that 6k threshold. 

>but this similar reimbursement from the previous month wasn't

While in January it did not added up to that.

So if that happened (I did not check but you can easily do so) the second reimbursement you linked is totally legal.

**Comment by cuducos** [comment]
@jtemporal nailed it.

The reimbursement you mentioned was claimed in Feb. 2017, a total of 5,851.30 BRL. That reimbursement together with [this one also claimed in Feb. 2017](https://jarbas.serenatadeamor.org/#/year/2017/applicantId/2916/documentId/6203019) extrapolates the [limit for the fuel subquota](https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/CEAP.md). This second one valeu is 199.51 BRL. 

So far the reference reimbursement you linked is the only reimbursement made for fuel in Jan. 2017. Does that make sense?

**Comment by vncscoelho** [comment]
That's it @jtemporal. I wasn't aware of the limit for that sub quota.

**Comment by jtemporal** [comment]
awesome @vncscoelho ;)
