### ISSUE TITLE
Browseable Dashboard

### ISSUE THREAD

**Issue by chessbr** [datasciencebr/serenata-de-amor#267]
Hi guys!
First, congratulations for the awesome work you are doing!

I have some features to share with you and probably all of you have imagined this before.
I know that collecting and processing federal data is already a challenge and I also know you have plans to start collecting data from states and also cities which is really very good, I will start to scrap data from my city soon so be ready for that.

This project makes an extraordinary public service, showing suspicious activities from congressmen/congresswomen but that is the top of the iceberg.

Although we have transparency laws that should be respected by all national institutions, that data is almost hidden from the population. Almost anyone want to search for all the receipts, documents, spreadsheets to see if everything is ok, if our taxes are being correctly applied and to where it is going.

That said, I really hope that this project, some day, could provide us a dashboard for each state and city about all the governmental expenses (huge challenge right) and also claim for the population to help scrapping data from their cities (we need a standard) so we can all help this happen.

I know data science is based of formulated questions that we need to answer to propose a way to solve that, but you probably feel what almost every citizen of this country feels, **what happens to our taxes**?

I hope we start a good discussion about this :)

Thanks.

**Comment by cuducos** [comment]
> That said, I really hope that this project, some day, could provide us a dashboard for each state and city about all the governmental expenses

We have it by state in an _ad aeternum_ work in progress at [Jarbas Dashboard](https://jarbas.datasciencebr.com/dashboard) — but I think contributions in that sense would better fit this [Jarbas issue](https://github.com/datasciencebr/jarbas/issues/61) — what do you think?

**Comment by cuducos** [comment]
Closed by inactivity
