### ISSUE TITLE
Jupyter Notebook not available (docker)

### ISSUE THREAD

**Issue by vantonini** [datasciencebr/serenata-de-amor#274]
Hi guys! I noticed that I couldn't access jupyter notebook following the documentation (steps 3 and 4 from CONTRIBUTING - Docker Installation Environment) because I had to set an ip to jupyter through this command: 
`jupyter notebook --ip 0.0.0.0 --no-browser`
I don't know if this only happens because I'm using docker for Windows, but maybe we could put it to the CONTRIBUTING file?

**Comment by arioston** [comment]
Hi, I guess the problem is with the command :

> 4. You can start Jupyter Notebooks and access them at localhost:8888: $ docker-compose run --rm research jupyter notebook

on [Doc:](https://docs.docker.com/compose/reference/run/)

> docker-compose run command does not create any of the ports specified in the service configuration. This prevents port collisions with already-open ports. If you do want the service’s ports to be created and mapped to the host, specify the --service-ports


I hope this fixes the problem.

**Comment by anaschwendler** [comment]
Closed by #287
