### ISSUE TITLE
New descriptive analysis

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#295]
One of our collaborators (non-tech) suggested a descriptive analysis we could use as argument when standing for better control and transparency of CEAP expenses. She suggested a notebook addressing question such as:

1. Monthly average per congressperson (grouped per state, as values varies across states)
2. Monthly ratio of the total allowed and the total spent per congressperson (grouped per state, as values varies across states)
3. Monthly average per subquota (grouped per state, as values varies across states)

This numbers will help us give the proper dimensions for the problem, for example.

**Comment by silviodc** [comment]
I would also to include the average life cost of the capital of each state and median of salary that people gets there. I have seen many people on Twitter saying that deputies lives in another world an don't represent them, due the high value available on CEAP.

**Comment by mathcunha** [comment]
Dear @cuducos,

The info to answer questions 1 and 3 can be found at 2017-07-04-reimbursements.xz, something like groupby(['year_month', 'state', 'congressperson_name'])['total_net_value'].mean() for question 1 and groupby(['year_month', 'state', 'subquota_description'])['total_net_value'].mean() for question 3. The complete solution is available at https://github.com/mathcunha/serenata-de-amor/blob/master/research/develop/2017-11-25-mathcunha-ceap-expenses-descriptive-analysis.ipynb.

But, to answer Question 2, I have to now the total allowed. Is there any dataset where this information is stored? I have just found it at http://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/cota-parlamentar.

Thanks

**Comment by cuducos** [comment]
Closed by #297
