### ISSUE TITLE
Add pyup

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/serenata-de-amor#299]
Pyup is a feature that keep all of the libraries updated.
We already have pyup in our other repositories, like `rosie` and `serenata-toolbox`

_Contributors_: It is a good issue for `first-timers`, so if you know someone who is interested in contributing, but didn't know how, teach someone :)

**Comment by shuchitagupta** [comment]
I am a first timer. How can I go about contributing? Thanks

**Comment by cuducos** [comment]
Hi @shuchitagupta : )

I'm not sure about your experience with Git and GitHub, but the very basic are these [6 steps](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#the-basics).

Besides that pyup.io documents how it works and how to add it to a GitHub repository. I already enabled it to this repo, but one might need a config file and a bagde on the `README.md` — we'd be happy if you could add those ; )

**Comment by cuducos** [comment]
Also we do not want to specify the version of `serenata-toolbox` so always the newest version is installed. We need to add code do pyup.io ignores this package ; ) All documented in pyup.io

**Comment by shuchitagupta** [comment]
@cuducos I dont understand completely how to add. A little more help will be appreciated. Thanks.

**Comment by cuducos** [comment]
Hi @shuchitagupta,

In order to help you, may you share what you've tried, read, tested?

For example: I'm not sure if your doubts are related to contribution over Git e GitHub or specifically about pyup.io. As I've already shared a link about Git/GitHub, here's a link about how to setup pyup.io: https://pyup.io/docs/bot/config/

What do you think?

**Comment by shuchitagupta** [comment]
@cuducos I have added a config file and pushed it onto a branch

**Comment by cuducos** [comment]
> I have added a config file and pushed it onto a branch

Great! Have you forked the project to your account (there's a _Fork_ button on the top part of every GitHub project)? If so now it's time to push you branch to your fork (e.g. `git push origin name-of-the-branch`).

Once your branch is pushed to your fork, when you open your fork at GitHub there'll be a button to open a Pull Request. That's the way you get code suggested into this project ; )

**Comment by shuchitagupta** [comment]
Yes. I understand this. I think I am doing something wrong. I have followed the same but unable to get a pull request.

**Comment by cuducos** [comment]
Ok… so I understand [this is your  fork](https://github.com/shuchitagupta/serenata-de-amor). However I can't find your branch in [its branches](https://github.com/shuchitagupta/serenata-de-amor/branches) nor your commits among [its commits in the `master` branch](https://github.com/shuchitagupta/serenata-de-amor/commits/master). So I guess the step you're not succeeding is in pushing your changes to your fork.

What's the output of the command I suggested in my last message?

**Comment by shuchitagupta** [comment]
I have added branch pyup_branch and now tried fun_stuff branch

Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/shuchitagupta/serenata-de-amor.git
 * [new branch]      fun_stuff -> fun_stuff

**Comment by cuducos** [comment]
Hi @shuchitagupta 

> I have added branch pyup_branch and now tried fun_stuff branch

Take a look in this output you just shared:

```
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/shuchitagupta/serenata-de-amor.git

[new branch] fun_stuff -> fun_stuff
```

For some reason your branch is not called `pyup_branch` as you expeced, buy `fun_stuff`. And it is indeed in your fork: I can [see the branch](https://github.com/shuchitagupta/serenata-de-amor/tree/fun_stuff) now, and [it is listed](https://github.com/shuchitagupta/serenata-de-amor/branches) in your fork's branches.

In this list page, in the left part of the `fun_stuff` table row there's a button _Compare_ so you can compare the changes from your branch to our `master` branch and open a PR.

**Comment by shuchitagupta** [comment]
Hi,
Is this right?
![image](https://user-images.githubusercontent.com/6664686/34106115-f9e47850-e41c-11e7-9d0e-c5d10d7a81cd.png)

**Comment by cuducos** [comment]
> Is this right?

It depends : ) It's right in the sense it's showing you that there's nothing different comparing your branch `fun_stuff` to our `master` branch. This is precisely correct.

However I do understand you expected to see your changes (the config file) there. It might have happened that this file was committed to another branch. You have to locate that branch, change to it with `git checkout name-of-the-branch` and then push it to te remote repo with `git push origin name-of-the-branch`.

Then when comparing the branch tat has your config file with master it should pop up there ; )

**Comment by shuchitagupta** [comment]
I was successful now. Added a config file for pyup and created a pull request.

**Comment by shuchitagupta** [comment]
@cuducos Thank you for the help and patience.
