### ISSUE TITLE
Include telegram badge to README.md

### ISSUE THREAD

**Issue by anaschwendler** [datasciencebr/serenata-de-amor#301]
There is a way to include our telegram as a badge on github, the library is [here](https://github.com/Patrolavia/telegram-badge)

Our group on telegram: https://telegram.me/joinchat/AKDWc0BDOqriD1n-mntRBg

**Comment by anaschwendler** [comment]
Talking with @cuducos we decided that we don't want to do it right now :)

**Comment by cuducos** [comment]
Just to clarify: the Telegram group is for devs interested in contributing, so the `CONTRIBUTING.md` is the proper place for the link (and there it is, in the very first paragraph). No need to call more attention repeating it in the general-public `README.md`.
