### ISSUE TITLE
Invitation to Telegram group expired

### ISSUE THREAD

**Issue by jirka66** [datasciencebr/serenata-de-amor#323]
The invitation links for the Telegram group  expired, returning the following error in the web interface:

call
https://t.me/joinchat/EL96zkOUq4UK4Cv1-o5OYQ

my line when there is a bug:
https://web.telegram.org/#/im?tgaddr=tg:%2F%2Fjoin%3Finvite%3DEL96zkOUq4UK4Cv1-o5OYQ

Error:
Method: messages.checkChatInvite
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}

**Comment by anaschwendler** [comment]
Hi @jirka66!

We took a closer look at our Telegram link, and for us, both in the website and in the `CONTRIBUTING.md` they seem to be working.

Can you try again, please? https://telegram.me/joinchat/AKDWc0BDOqriD1n-mntRBg

If they not work, please drop a line again! :)

**Comment by jirka66** [comment]
your address is different.

my error group
https://t.me/joinchat/EL96zkOUq4UK4Cv1-o5OYQ

**Comment by jirka66** [comment]
another group has logged out. I can not add it again. what's happening? Do I have the power of groups? I have 7 groups.

https://t.me/travelflexchat

**Comment by cuducos** [comment]
Sorry @jirka66 – we can only look after our Telegram group. If you have issues with other groups we definitively cannot help you. I suggest you to try to find people/repos related to the group you're linking. Wish you luck 🍀

**Comment by jirka66** [comment]
ok thank you
