### ISSUE TITLE
Website for consume API and publish data.

### ISSUE THREAD

**Issue by baltazarparra** [datasciencebr/serenata-de-amor#36]
Who will help this?

**Comment by pedrro** [comment]
Hi @baltazarparra, I can help that, can u contact me on telegram? pedrro2

**Comment by cuducos** [comment]
Hi @pedrro ; )

This issue emerged from Issue #34 — we did something very quickly (still struggling to put all the database online) to help @irio, but now we should discuss about different needs the project has. Some examples:

* Quick way to find info on a reimbursement (Issue #34)
* Institutional page
* Communication: publishing reports, press releases etc…
* what else…?

I think that talking in PVT (Telegram) might close the discussion for people bringing new/different needs. And having this specific discussion on the public Telegram group might leave some people behind due to its synchronous character.

In sum, this is such an important topic, and IMHO this asynchronous and open _forum_ is better to register needs, ideas… i.e. to understand exactly what problems this website should address.

Does that make sense?

**Comment by pedrro** [comment]
Yes, It totally make sense @cuducos, as I understood we have some work to do yet on the api layer, right? So, the idea that I have for now, is just start to create the "institutional page", that should be a static page with some informations about the project, we can start with data?

**Comment by cuducos** [comment]
Not much. Today there are [3 opened issues](https://github.com/datasciencebr/jarbas/issues):

* [One is already _in progress_](https://github.com/datasciencebr/jarbas/issues/6)
* [One I can easily code tomorrow](https://github.com/datasciencebr/jarbas/issues/2)
* [And one I just waiting](https://github.com/datasciencebr/jarbas/issues/5) for @irio's feedback (our main user, the guy who raise the issue that gave birth to [Jarbas](https://github.com/datasciencebr/jarbas))

Therefore I see no problem in you guys focusing — if you want — in the more definitive website. The _quick fix_  is just mostly an internal tool and is already useful I guess.

**Comment by baltazarparra** [comment]
@pedrro then we can start the scope of the definitive site . We do front already thinking of how to consume the api, right @cuducos ?

**Comment by cuducos** [comment]
>  We do front already thinking of how to consume the api

I'd say we need a step back. We need to clarify what needs we have. Some starting points would be:

* Talk to [Pedro](http://telegram.me/vila_pedro), our journalist, and check what structure he would need to put the communication strategy forward, including reports and press releases
* Talk to @cabral and @brunopazzim and check with them any kind of institucional and strategic contents we might need to have on the website as they are kind of community managers and speak about the project and about the crowd funding campaign with a lot of people
* Talk to @irio and see if from his perspective he has anything specific to the website besides consuming the API
* Ask the community if is there any other need or people that would like to voice their point of view regarding what the website could have

The idea **is not** to just compile every word people say about it and just do it. The idea **is** to better understand the specific *problems* the website have to address. Without that in mind, I think it would be difficult to design anything in terms of technology, UI or UX.

**Comment by baltazarparra** [comment]
completely agree @cuducos. The current status is to think and structure the information we have and how we provide. When I say we should start the site, is exactly that. Information Architecture.

- _sorry for mediocre english_

**Comment by cuducos** [comment]
> sorry for mediocre english

Don't worry at all — it's working perfectly ; )

**Comment by prcastro** [comment]
Maybe a good approach is to set up a Docker environment, with a container for a DB, a container for the API, etc. All being orchestrated using Docker Compose. With this, we can deploy the web server fast, anywhere and in a reproducible manner.

**Comment by Irio** [comment]
Already created and open sourced at https://github.com/datasciencebr/jarbas.
