### ISSUE TITLE
Pack common tools in a specific module

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#37]
While coding, planning to code or code reviewing I'm starting see a lot of repetition. My intention is to create a new module (`tools/` maybe) with tools to be used by anyone in other scripts (setting up scripts from `src/`, exploring and analyzing data in `develop/` etc.).

Anyone is free to join me in this, we can schedule and pair as this has no urgency at all.

And anyone can contribute listing functions that could be inside this module. I get started:
- list path to the CSV (`.xz`), i.e. the existing datasets
- load translations
- list all record (with or without filters) from the datasets
- …

**Comment by Irio** [comment]
Been having this need for some time already, but just thought about an issue: Jupyter Notebooks are supposed to be totally reproducible; analyses we have, if ran again, should generate the exact same results. e.g. If I use a function `load_dataset('all')` in my analysis, its output might change when the function receives a patch.

Personally believe that having these functions will come for the better, even if bringing this issue with them. If we start noticing real problems, we could always use [`inspect.getsourcelines`](https://docs.python.org/3/library/inspect.html#inspect.getsourcelines) inside the notebook.

**Comment by cuducos** [comment]
I'd add to the list:

*

**Comment by cuducos** [comment]
Fixed by [serenata-toolbox](https://github.com/datasciencebr/serenata-toolbox) (even if we have to actually use it in this repo, as in #143)
