### ISSUE TITLE
Find expenses in brothels

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#39]
Brothels will usually print receipts using companies with names and main activities more "morally acceptable", e.g. a restaurant. If we can gather a list of CNPJ's from the major brothels in Brazilian capitals, this could generate a very interesting report and news coverage.

Original idea by Pedro Vilanova.

**Comment by cuducos** [comment]
I think we might gather great data with something as simples as a Google Form and a social media campaign (cc @tatianasb)

**Comment by camilagss** [comment]
For Rio de Janeiro's data you can export [Bitchmaps' KML](https://www.google.com/maps/d/u/0/viewer?mid=1966bBklf94Uj5glEZGRigecFa60&hl=pt_BR).

**Comment by ruivelocci** [comment]
Great data @camilagss. I think if we compare the time of spend with your presence on SESSION/CPI with that we can find "Strange Things".

**Comment by rafaelalmeida** [comment]
What data does the receipts offer? @camilagss 's KML is great, but do most receipts have addresses, so we can geocode and match? How can I find some sample receipts?

**Comment by Irio** [comment]
@rafaelalmeida Run `python src/fetch_datasets.py` and you'll get [a dataset](https://github.com/datasciencebr/serenata-de-amor/blob/c5439d947812ec40948eb445f7badf77dc6ad0e5/src/fetch_datasets.py#L31) with latitude/longitude of all companies in the receipts will be downloaded. It's `data/2016-09-03-companies.xz`.

https://github.com/datasciencebr/serenata-de-amor/pull/19

**Comment by iGallina** [comment]
Politicians usually use the home delivery service and pay in cash for this kind of service.
Or get someone else to pay for them, which is more common.
We should focus on what is left out of the auditing or focus on what is being wrongly declared?

**Comment by guilhermeprokisch** [comment]
Another source could be the
http://www.wikisexguide.com/

For example:
http://www.wikisexguide.com/wiki/S%C3%A3o_Paulo

**Comment by guilhermeprokisch** [comment]
If I have time I will think how to create a webscraper for this website, they have the address of many places, we can check possibles "fake companies names", looking the address.

**Comment by guilhermeprokisch** [comment]
Hey Guys. I think I can do a CSV with the http://www.wikisexguide.com/ containing the Name, Category, Localization, and Phone.  I will try to open a request Pull in some days.

**Comment by guilhermeprokisch** [comment]
Hi Guys. 

I realized that his website just has information's mainly for São Paulo and Rio and no have too many places.  
Anyway... I get all the data available for São Paulo and Rio and I made a simple crawler.

This is the my crawler https://github.com/guilhermeprokisch/wikisexspider

and here is the output in CSV.

https://github.com/guilhermeprokisch/wikisexspider/blob/master/wikisexguide/output.csv

**Comment by cuducos** [comment]
Hi @guilhermeprokisch! Many thanks for that.

Even with data restricted to São Paulo and Rio de Janeiro I think this is useful. 

I strongly encourage you to adapt that and send a PR to our `/src`. By adapting I mean:

* Make sure `scrapy` is installed within Serenata Conda environment
* Add a reference to the script/module in `CONTRIBUTING.md`
* Add a date prefix and compact the `.csv` output (eg. `2016-11-03-cat-houses.xz`)

One doubt: I see [you restricted the cities to São Paulo and Rio de Janeiro](https://github.com/guilhermeprokisch/wikisexspider/blob/master/wikisexguide/wikisexguide/spiders/wikisexguidespider.py#L11) (as you said before, the main cities in this website database). Does it worth it to include more cities, even if we don't have a lot of results from them?

I'd be happy to help you in any of these issues, pairing, discussing on Telegram (same username as in here) etc. What do you think about it?

**Comment by guilhermeprokisch** [comment]
Hi @cuducos 

I create this temporary repository 
https://github.com/guilhermeprokisch/congress_cats_distance
> Include the _2016-09-03-companies_ to run the _measure.py_

You can take a look and tell me how to organize this in Serenata.

> I found some funny results: Look the [here](https://github.com/guilhermeprokisch/congress_cats_distance/blob/master/companies-cat-house-distances-analysis.ipynb)

About your doubt:  The I need to take a look the website to check if others cities also have informations.

**Comment by cuducos** [comment]
Sure thing, @guilhermeprokisch!

I have already gone through your code, it looks pretty good.

Your scrapy module could be a module inside our `/src` directory and your `.ipynb` would go to `/develop` — does that make sense? You can fork and clone this repo, move your code to these places, document the `/src` into `CONTRIBUTING.md`, generates the compressed CSV (`.xz`) according to the [naming recommendations](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#best-practices) etc.

We can do it in pair programming or you can send a PR and in the code review cycles I help you putting everything in the right place. How does it work better for you?

**Comment by cuducos** [comment]
Closing this: @guilhermeprokisch made a great contribution on #117 and we're refactoring it at #123 — further discussion is welcomed there.
