### ISSUE TITLE
Find health expenses

### ISSUE THREAD

**Issue by tatianasb** [datasciencebr/serenata-de-amor#44]
According to this [**link**](http://congressoemfoco.uol.com.br/noticias/lista-todos-os-salarios-e-beneficios-de-um-deputado/) the representatives can only be indemnified for health expenses that are not offered by the [**DEMED (Departamento Médico da Câmara / Medical Department of the Lower House**)](http://www2.camara.leg.br/a-camara/estruturaadm/demed)

So we could also look for irregularities regarding this subject also.

**Comment by hyena22** [comment]
Correct me if I am wrong but there does not seem to be any subquota_description category related to health.

**Comment by cuducos** [comment]
@hyena22 indeed. @cabral or @irio: would it worth it to write Lucio and try to understand why this topic on _health_ was raised in this article (as he works for this outlet)? If it's reimbursed through the CEAP we might be missing something here…
