### ISSUE TITLE
Share final data on Kaggle community

### ISSUE THREAD

**Issue by pingfreud** [datasciencebr/serenata-de-amor#45]
Kaggle's community is very large, the users are willing to help noble causes and the technical skills of the top tiers are amazing.

I shared some data I webscrapped describing terrorist attacks and got contributions from several users.

https://www.kaggle.com/argolof/predicting-terrorism

I think the project can make use of Kaggle to increase predictive performance and maybe get some different perspectives from people around the globe.

**Comment by Irio** [comment]
EXCELLENT idea, @pingfreud. Could you help us with this publication? I personally never posted any dataset there.

**Comment by pingfreud** [comment]
Yes, Irio.

I'm fascinated with the idea. Congratulations. I didn't have time to get familiar with the environment and the project details yet, but I'll get back to you in the communication channels in the next few days.

**Comment by Irio** [comment]
https://data.world/ is another community that can receive the datasets well.

**Comment by Irio** [comment]
Jarbas already has [the dataset documentation](http://jarbas.datasciencebr.com/static/ceap-datasets.html) and the issue #105 proposes a translation of the Bureau Act regulating the quota, so we can probably publish the datasets as soon as the last issue gets done.

**Comment by cuducos** [comment]
I'm closing this since further discussion can be added in PR #52, ok?
