### ISSUE TITLE
Data from candidates in 2016 elections (Dados de candidatos nas eleições 2016)

### ISSUE THREAD

**Issue by VitorVRS** [datasciencebr/serenata-de-amor#49]
Caso seja do interesse, foi disponibilizada uma forma de ver os dados dos candidatos das eleições 2016 de todas as cidades do país:
http://www.tse.jus.br/eleicoes/eleicoes-2016/divulgacao-de-candidaturas-e-contas-eleitorais

Contém informação de bens declarados pelos candidatos.

Aparentemente o scrapping é fácil.. exemplo de um candidato: http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/buscar/2016/86517/2/candidato/210000011570

Parabéns pelo projeto.

**Comment by josircg** [comment]
Não precisa fazer scrapping Vitor. Dá para pegar direto o ZIP:

http://www.tse.jus.br/hotSites/pesquisas-eleitorais/candidatos_anos/2016.html

**Comment by phdabel** [comment]
Eu comecei a desenvolver um app em nodejs para alimentar um banco de dados mongodb a partir dos zips. O app abre cada um dos zips, parseia e armazena em documentos mongo. São dados referentes aos candidatos, partidos, número de votos e bens.

A ideia era fazer a coleta desses dados e disponibilizar via API.
Se já não foi feito algo parecido posso trabalhar para disponibilizá-los.

No mesmo projeto há busca de dados das sessões da câmara de deputados.
Nesse caso não é armazenado, pois é muita informação.
Mas os dados podem ser obtidos diretamente através de um webservice da câmara de deputados.
A única coisa que o app faz (se não me engano) é converter a saída para json, uma vez que ela originalmente é em xml.

**Comment by phdabel** [comment]
Está em um repositório privado do bitbucket, mas pretendo disponibilizá-lo em um repositório aberto do github.

**Comment by cuducos** [comment]
Hi guys, thanks for this discussion.

Would you mind changing the language to English if possible? Some contributors and some people following the project are not Brazilians.

Something is still unclear for me: what kind of hypothesis are you considering by bringing in declared goods & properties? Like… try to find out if a congressperson pays rent in a city he owns some property? That looks interesting ; )

**Comment by phdabel** [comment]
Analysing the evolution of their declared goods by time given some other metric such as: quantity of votes or lawsuits.

**Comment by josircg** [comment]
@phdabel it would be great to have this API. If you provide the API, I can make a front-end to let end users to access it.

**Comment by cuducos** [comment]
Sounds good : ) Thanks for the clarification

**Comment by phdabel** [comment]
@josircg I can work on it. But it will take some time. The parser of the zips is generic but I have to make a template for each model. Then I can easily provide the API endpoints. I have a registered domain name but I'd need to configure the host server too.

**Comment by fernandoGuisso** [comment]
Awesome, I'd like to have this too.
First I'd make an angular app to consume (http://divulgacandcontas.tse.jus.br/divulga/rest/v1/), just for simplify the interface to the citizens of my city, maybe a comment page per candidate.

**Comment by ribeiroevandro** [comment]
Alguém está tendo problemas de CORS usando essa API? Pra mim simplesmente parou de funcionar e não estou encontrando uma solução e nem outra API, tinha feito a listagem dos candidatos aqui da cidade, porém agora queria colocar quem foi eleito e quantidade de votos, mas não estou conseguindo... Se alguém tiver uma luz...

**Comment by pedrommone** [comment]
@ribeiroevandro there are no CORs `header`, you need use a proxy or build an API on the top of it.

```
 % curl -I http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/buscar/2016/86517/2/candidato/210000011570
HTTP/1.1 200 OK
Server: thttpd/2.26 ??apr2004
Content-Type: application/json
F5-IpCliente: 72.246.216.224
ClientIP: 72.246.216.224
X-Powered-By: SEREDE/COINF/STI/TSE
Content-Length: 5754
Date: Mon, 03 Oct 2016 11:23:24 GMT
Connection: keep-alive
X-N: S
```

If you want use a proxy (the easiest way) I sugggest you use https://github.com/gr2m/CORS-Proxy

**Comment by cuducos** [comment]
@ribeiroevandro maybe you were blocked after too many request. Have you tried @pedrommone's idea of trying a proxy?

**Comment by cuducos** [comment]
This data collection is advancing in #196, so I'm achieving this discussion.
