### ISSUE TITLE
Find public contracts with prices and people responsible for it

### ISSUE THREAD

**Issue by rroriz** [datasciencebr/serenata-de-amor#57]
Products and services acquired by the government must use a public contract.
This can be searched [here](http://www.comprasgovernamentais.gov.br/).
We can scrape values, agencys and people involved with some contracts that may look suspicious.
Example: contracts that don't need biddings (pt-br: "licitações");

**Comment by cuducos** [comment]
Hi @rroriz — that looks interesting.

Nowadays our main dataset is from [CEAP](http://www2.camara.leg.br/participe/fale-conosco/perguntas-frequentes/cota-para-o-exercicio-da-atividade-parlamentar) — which does not require public bids or contracts.

Just to clarify: are you proposing another branch of analysis or to draw some hypothesis linking these public bids & contracts to CEAP data?

**Comment by rroriz** [comment]
I was proposing a new branch of analysis.
But after reading more about CEAP, there is something that can be linked with biddings: some expenses could be the subject of a bidding . 

I'm closing this issue until I have something more concrete to do with biddings.
