### ISSUE TITLE
Create TL;DR of Bureau Act describing the CEAP

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#69]
No legalese allowed in this document. It is expected to be written just in Portuguese, since the data journalists are all fluent in the language.

Check "Texto Atualizado" at http://www2.camara.leg.br/legin/int/atomes/2009/atodamesa-43-21-maio-2009-588364-norma-cd-mesa.html for the original text.

**Comment by anaschwendler** [comment]
Atende as seguintes despesas:
1.  É destinado a custear gastos exclusivamente vinculados ao exercício da atividade parlamentar.
2. Atende as seguintes despesas:
- Passagens aéres
- Telefonia
- Serviços e produtos postais, mas **não a compra de selos e remessa de cartões postais**
-  Manter escritório de apoio a atividade parlamentar, contando com
    - Aluguel, condomínio, IPTU + seguro contra incêndio
    - Serviço de energia elétrica, água e esgoto
    - Alguel de móveis e equipamentos, junto com material de expediente e suprimentos de informática
    - Assinatura de TV a cabo ou similar e internet
    - Locação e assinatura de licença de código
- Assinatura de publicações (revistas, jornais, ...)
- Alimentação do parlamentar (**apenas do parlamentar**)
- Hospedagem do parlamentar, **exceto no Distrito Federal**
- Despesas com locomoção
    -   Aluguel ou  fretamento de aviões e embarcações
    -   Passagens terrestres, marítimas ou fluviais
    -   Aluguel ou fretamento de carros, **até R$ 10.900,00 reais mensais**
    -   Serviço de táxi + pedágio + estacionamento, **até R$ 2.700,00 reais mensais(ao total dos três)**
-   Combustíveis + lubrificantes, **até R$ 6.000,00 reais mensais**
-   Serviços de segurança, por empresa especializada **até R$ 8.700,00**
-   Contratação para **apoio da atividade parlamentar** de consultoria e trabalhos técnicos, permitindo pesquisa socioeconômica
-   Divulgação da atividade parlamentar, **exceto nos 120 dias anteriores a eleição federal, estadual ou municipal**, exceto se o deputado não for candidato.
-   Participação em cursos, palestras, seminários, simpósios, congressos ou eventos do mesmo gênero, **realizado por instituição especializada**, **até o limite de 25% do valor da menor cota mensal (R$ 7697.16) por mês**
-   Complementação do auxílio moradia, **até R$ 1747,00 reais mensais**

**Comment by anaschwendler** [comment]
Pode utilizar mais R$ 1353,04 reais, o deputado que for:
- Líder ou vice-líder de partido político, bloco parlamentar ou da Minoria
- Líder ou vice-líder do Governo na Câmera dos Deputados ou Congresso Nacional, **se Deputado Federal**
- Presidente ou Vice-Presidente de Comissão Permanente
- Representantes de Partidos Políticos **com menos de um centésimo** da composição da Câmara dos Deputados
- Se um mesmo deputado ocupa mais de um cargo simultâneamente, o valor **não se acumula**
- Deputado que for representar o Brasil em missão no mercosul pode gastar mais 20% do valor da menor cota, por viagem

**Comment by anaschwendler** [comment]
Artigo 3 - A cota pode ser usada da seguinte forma:
- Por meio de serviços disponibilizados pela Câmara dos Deputados
- Mediante reembolso, inclusive em caso de despesas realizadas por meio eletrônico

Artigo 4 - Reembolso é efetuado mediante requerimento padrão, assinado pelo parlamentar, que assume inteira responsabilidade pela despesa, atestando que:
- O material foi recebido, e em caso de serviço, atestando que o serviço foi realizado
- O objeto do gasto obedece aos limites estabelecidos na legislação
- A documentação é autêntica e legítima

1. Os reembolsos relativos a cota são de caráter indenizatório.
2. Só pode ser resarcida despesa comprovada por documento original, **em primeira via**, quitado e em nome do deputado ressalvado quando:
    - Conta telefônica: apenas a apresentação da folha de rosto, acompanhado do comprovante de pagamento
    - Contas de água, esgoto, telefone e energia elétrica, bem como condomínio e IPTU, em nome de proprietário do imóvel, **desde que o endereço do documento coincida com o imóvel cadastrado junto à Coordenação de Gestão de Cota Parlamentar**
    - Pode ser comprovado por meio de cupom fiscal ou nota fiscal simplificada paga, mesmo que **não contenha nome do beneficíario do produto**
3. O documento que comprova o pagamento **não pode ter rasura, acréscimos, emendas ou entrelinhas**, deve conter data e deve conter os serviços ou materiais descritos item por item, **sem generalizações ou abreviaturas**, podendo ser:
    - Nota fiscal hábil segundo a natureza da operação, impressa dentro da validade
    - recibo assinado, contendo identificação e endereço completos do beneficiário do pagamento, **no caso de pessoa jurídica comprovadamente sem obrigação de gerar documento fiscal**
    - bilhete de passagem
- Recibo de pessoa física:
    - Aluguel de imóvel
    - Alguel ou frete de aeronave ou embarcação, que deve conter a identificação de quem usou o serviço, especificação da data e trecho percorrido e número da permissão para o uso do serviço.

4, 5 e 6: Estão no item 2.

7. Essas notas devem estar em sistema informatizado próprio
- Os registros dos comprovantes de despesa, relacionados em requerimento padrão
- Imagens digitalizadas dos comprovantes

8. No caso de aluguel ou fretamento de aeronave, o documento deve especificar o **trecho, período do voo e prefixo da aeronave empregada**

9. **Não será reembolsado despesa com aquisição de material permanente** (Aquele de duração superior a dois anos. Exemplos: mesas, máquinas, tapeçaria, equipamentos de laboratórios, ferramentas, veículos, semoventes, etc. Fonte: Tesouro Nacional), **nem de gênero alimentício**

10. A apresentação da documentação deve ser no máximo até 90 dias após o fornecimento do produto ou serviço

11. **Não há resarcimento se o bem adquirido ou serviço prestado for de propriedade do deputado ou parente seu até terceiro grau**

Sobre o item de uso da cota para ursos, palestras, seminários, simpósios, congressos ou eventos do mesmo gênero: 
- Para acontecer o reembolso o deputado não pode faltar as sessões e reuniões, em caso de falta é efetuado glosa proporcional ao período de ausência
- **Gastos com educação básica, graduação e pós-graduação não são válidos.**
- O parlamentar deve apresentar comprovante de participação emitido pela instituição organizadora e relatório de atividades no período.

**Comment by anaschwendler** [comment]
Artigo 5. Sobre transporte aéreo e de serviços e produtos postais podem ser feitos desde que sejam comprovados com Requisição de Passagem Aérea (RPA) e Requisição de Serviços Postais (RSP)
- Ambos são válidos até o último dia útil do exercício financeiro respectivo;
- **Ambos serão emitidos pelo sistema de controle de cota e deve ser assinado pelo Deputado ou servidor interessado**
- O bilhete de passagem é fornecido mediante entrega do RPA, **e só pode ser feita à empresa cadastrada previamente**
- A emissão do bilhete deve ser feita pelo deputado ou servidor devidamente credenciado
- A retirada do bilhete em nome de acessores exige registro do fato em sistema até o primeiro dia útil do mês seguinte a emissão da passagem
- A RPA e o bilhete não podem ser convertidos em ordem de crédito de passagem

Artigo 6. As empresas de transporte aéreo credenciadas devem informar, quando solicitado, informações detalhadas dos bilhetes emitidos

Artigo 7. Se o bilhete emitido é contra as normas, é descontado automaticamente em folha de pagamento

Artigo 8. Despesas com telefone só são reembolsadas quando comprovadas que são de responsabilidade do deputado.
- Todos os gastos passíveis de reembolso são correspondentes a comunicação em geral, como acesso a internet, aluguel e instalação de equipamentos destinados a comunicação por voz ou dados
- A comprovação da despesa por telefone se dá mediante apresentação da folha de rosto da conta, acompanhada de comprovante de pagamento.
- Em caso de extravio de conta, e possível comprovar com segunda via emitida pela operadora, acompanhada de declaração de extravio assinada pelo deputado.

Artigo 9. Não é admitido aluguel de imóvel que pertença ao próprio deputado ou qualquer entidade que ele tenha participação

Artigo 10. **Os contratos de aluguel de bens móveis não permitem a compra do móvel com utilização da cota**
- Aluguel de carro não inclui serviço de motorista, e só pode ser feito por empresa jurídica, podendo ser incluso o seguro.
- O carro deve pertencer a empresa, fato comprovado com a apresentação do CRVL do veículo
- O resarcimento do aluguel do veículo é limitado a 10% do valor de mercado do veículo, utilizando a tabela FIPE

Artigo 11. A cota é calculada proporcionalmente ao período de efetivo exercício no mês.
- Se um deputado é removido ou adicionado, tem preferência a cota àquele que regista presença, se ambos estão presentes, atribui-se ao titular do mandato, ou em caso de sucessão de suplentes atribui-se ao de maior ascendência na ordem de suplência
- Caso haja convocação de suplente, não há redução da cota.

Artigo 12.**O uso da cota se restringe ao período do mandato**, desde que não haja convocação de suplente

Artigo 13. **O saldo da cota não se acumula ao longo do exercício financeiro**

Artigo 14. A cota não pode ser adiantada, transferida de um beneficiário para outro.

Artigo 15. **Não é permitido gasto de caráter eleitoral**

**Comment by cuducos** [comment]
Great work! Let's publish it? Where? We can convert it do `.md` and add to the repo, or as a linked Gist, whatever…
