### ISSUE TITLE
Benford analysis on net values as features.

### ISSUE THREAD

**Issue by pingfreud** [datasciencebr/serenata-de-amor#73]
Since we are auditing data, Benford analysis came as a first thought.

For those unfamiliar with the topic, we compare the distribution of leading digits in the data with the naturally expected distribution.

Intro - https://en.wikipedia.org/wiki/Benford%27s_law
More info - https://www.agacgfm.org/AGA/FraudToolkit/documents/BenfordsLaw.pdf

On one hand, it should NOT be directly applied to human generated values (such as service prices), however we can use deviation measures (absolute difference, squared difference,etc.) and sample statistics as input for other classification algorithms in our framework.

I started a notebook using R "benford.analysis" package to perform basic exploration in the data. I also started to develop the "benford.subquota" function to extract features from the serenata_de_amor dataset.

Notebook: https://github.com/pingfreud/serenata-de-amor/blob/R-analysis/develop/2016-09-20-im-benford-analysis.ipynb
Function: https://github.com/pingfreud/serenata-de-amor/blob/R-analysis/develop/benford.subquota.R

I'm don't have formal training in programming, so code related feedback is extremely welcome. 

If you are willing to collaborate, check the pending goals in the files listed above. I would be happy to discuss other related topics.

**Comment by cuducos** [comment]
I think this idea is pretty much advanced in #52 — further discussion is welcomed there.
