### ISSUE TITLE
Telegram group link

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#75]
The link is not available anymore in the new `README.md` and not available in our website either.

**Comment by cuducos** [comment]
IMHO if the Telegram is in English to welcome people from abroad, the link should be here, in the English language medium ; )

**Comment by augusto-herrmann** [comment]
It's also not in the Contribution Guide.

**Comment by danalec** [comment]
telegram group link @ contribution guide is working, consider closing this issue

**Comment by cuducos** [comment]
Tks @danalec (and tks @cabral for the commit)
