### ISSUE TITLE
List of beneficiaries of Bolsa Família 

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#77]
Today a [friend tweeted](https://twitter.com/_Zamiliano/status/780747957960372224) that he had a document from Rio de Janeiro Public Prosecutor's Office with an attachment listing businesspeople who have been receiving Bolsa Família (a Brazilian social benefits focused on extreme poverty situation — i.e. certainly not businesspeople).

As we'll probably have names of partners in companies where congresspeople have spent CEAP money, and we can scrap (e.g. [from here](http://www.portaldatransparencia.gov.br/PortalTransparenciaPesquisaAcaoFavorecido.asp?Exercicio=2016&textoPesquisa=&textoPesquisaAcao=&codigoAcao=8442&codigoFuncao=08&siglaEstado=BA&codigoMunicipio=3313)) the names of people receiving Bolsa Família benefit.

We could spot more businespeople receiving the benefit (but according to @cabral this is a task already being done by Rio de Janeiro Public Prosecutor's Office), and also have a meaningful variable for our model.

**Comment by josircg** [comment]
The csv list can be downloaded via Portal da Transparência directly:

http://www.portaldatransparencia.gov.br/downloads/mensal.asp?c=BolsaFamiliaFolhaPagamento

However, it will be tough to do the match because the receiver is not identified by CPF. This list uses  NIT because generally people on extreme poverty never had the oportunity to get a CPF.

**Comment by cuducos** [comment]
Actually we might not need CPF. We can match name os beneficiaries with [`supplier`](http://jarbas.datasciencebr.com/static/ceap-datasets.html) field from CEAP datasets, and with the name of the partner of supplier (i.e. #16)…

**Comment by allantorres** [comment]
Maybe we can make references about the CPF of people in Bolsa Familia and companies who have received money from congresspeople ...

**Comment by caduvieira** [comment]
We must know that some of these people are MEI and their revenue may enable them to be part of the program.

**Comment by cuducos** [comment]
For those trying to collect this data, just fir fun I wrote a snippet that gets all the download URL from _Porta da Transparência_. Just sharing because it might help (maybe replace `yield` and `requests.head` and you have the basis to read remote data:

```python
import datetime
import warnings
import requests

STARTING_YEAR = 2011
NOW = datetime.datetime.now()
SERVER = 'http://arquivos.portaldatransparencia.gov.br/'
PATH = 'downloads.asp?a={}&m={:02d}&consulta=BolsaFamiliaFolhaPagamento'


def urls():
    for year in range(STARTING_YEAR, NOW.year + 1):
        for month in range(1, 13):
            if datetime.datetime(year, month, NOW.day) <= NOW:
                url = SERVER + PATH.format(year, month)
                req = requests.head(url)

                # looks like some devs are not familiar with 404 status
                if req.headers.get('Content-Type') == 'application/x-download':
                    yield url

                else:
                    msg = 'Data from {:02d}/{} could not be located at: {}'
                    warnings.warn(msg.format(month, year, url))


if __name__ == '__main__':
    for url in urls():
        print(url)
```

**Comment by luizfzs** [comment]
@cuducos i think your snippet should become part of the project, on src. It can be very helpful.

**Comment by cuducos** [comment]
@luizfzs This script alone does nothing, just list the URLs. If anyone else really starts to collect data probably she or he will go through this topic and probably gonna copy & paste it ; )

**Comment by pedrobarrostech** [comment]
I'm trying working it on it

**Comment by arnaldocorreiafilho** [comment]
In relation to question # 77 the data of the family bag is already working the code that downloads all the files will do a pull requeste and see if everything is ok.

**Comment by cuducos** [comment]
#187 has advanced a lot in this direction but either way [the analysis of frauds within _Family Allowance_ seems to be unfruitful](http://veja.abril.com.br/blog/radar-on-line/fraudadores-do-bolsa-familia-tinham-rendas-superiores-a-r-5-mil/) — so I'm closing this _issue_ I opened a couple of months ago. This doesn't mean it's useless — just that a) it's not a priority anymore and b) if anyone is still wanting to contribute the afore mentioned PR is idle.
