### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by pedrommone** [datasciencebr/serenata-de-amor#80]
I've open the issue datasciencebr/jarbas#21 also, is basically the same thing.

**Comment by dsakuma** [comment]
I'm working on it

**Comment by dsakuma** [comment]
Almost there! [Preview here](https://github.com/dsakuma/serenata-de-amor/commit/b8d2d0ae194db18601d9e174051da873d9f017d3)

**Comment by dsakuma** [comment]
I've opened the [pull request #83](https://github.com/datasciencebr/serenata-de-amor/pull/83), adding the dockerfile. Suggestions are welcome!

**Comment by Guilhermeslucas** [comment]
Is this issue still open? I can do that.

**Comment by cuducos** [comment]
Actually it's almost done in PR #83 — as far as I can remember we were just making sure the Jupyter Notebook IP address in the end of the documentation/instructions matched the container's IP. If you have any news on that, can you give a heads up in the PR so we can merge? I myself updated Docker and gonna try it today (cc @dsakuma @felipeclopes @gwmoura).

**Comment by vmesel** [comment]
Is this issue completely solved?

**Comment by cuducos** [comment]
Yep!
