### ISSUE TITLE
Discord channel

### ISSUE THREAD

**Issue by oxydron** [datasciencebr/serenata-de-amor#81]
On conversations on the main Telegram group, I verified that some people thinks that a Discord channel is a good way for us to communicate. Then I've created a channel (https://discord.gg/vhCbB3C) on Discord for Serenata do Amor.

I request, if you guys agree, to put the link on the description of the project, to inform people about the channel.

And by the way, I will pass the administration rights of the channel for the founders, any time.

Best regards and good work guys

**Comment by cuducos** [comment]
Please check #46 for this discussion…
