### ISSUE TITLE
Brazilian Air Force and congresspeople traveling for free

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#89]
This is not an issue. But I thought that I could document the suggestion here:

Brazilian Air Force aircrafts can be used by Brazilian officials (congresspeople included). Luckly they keep a very transparent record of who flew, when, and the departure and destination information: http://www.fab.mil.br/voos

Unfortunately it looks like this is not congresspeople preferred way to travel (just a few records of them), and Brazilian Air Force keep records of the title of the official (presidente of whatever), not of her/his name… this makes things difficult.

Anyway, people working with data on transportation (cc @Irio @andrepinho) might want to take a look.

**Comment by gabriel-almeida** [comment]
Maybe it is a good idea to put an "Archive" or "Low Priority" tag on this issue to keep things organized. 

Another information: a Wikipedia scraping should solves the mandate problem (https://pt.wikipedia.org/wiki/Lista_de_presidentes_da_C%C3%A2mara_dos_Deputados_do_Brasil) but it seems like many persons still aggregated by the same authority, unless a second source is provided, what might be confidential. And I'm looking for this pdf python package :)

**Comment by fcevado** [comment]
About pdf handling, there's any restriction to use `pandoc` or `pdf2text`? There are some python packages with bindings for both, I guess.
[pdf2text](https://pypi.python.org/pypi/pdf2text/)
[pandoc](https://pypi.python.org/pypi/pandoc/)

**Comment by cuducos** [comment]
No restrictions. I think this _Issue_ is idle because (as far as @gabriel-almeida pointed out) just the President of the Chamber of Deputies is allowed to travel in those aircrafts. Having [CEAP](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#more-about-the-quota-for-exercising-parliamentary-activity-ceap) as the focus makes this Brazilian Air Force dataset low priority for us, now.

However having the dataset ready to use could be useful for next phases of Serenata de Amor (when we work with other datasets beyond CEAP).

**Comment by cuducos** [comment]
Closed by inactivity
