### ISSUE TITLE
Add difficult level label to Issues

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#91]
This is a discussion started at #90. Main messages/excerpts:

By @leobiscassi:

>  I'd like suggest a thing to help with this. If maintainers add labels with level required to solve each issue will be cool for new contributors, like this: https://github.com/galaxyproject/galaxy/labels/friendliness%2Fintermediate

Then some people cheered and I added:

> Not sure how to ponder on the difficulty of each issue. For example, I'm kind of experienced in development, so issues regarding general scripts, tests, setup tends to be easy for me, it would mean I would mean most of these would be easy or medium. However I never played around with Pandas, or Altair, or Seaborn, nor with scrapping… so analysis or data collection, even if I'm an intermediate/advanced Python developer, would be hard for me. Anyway, if you wanna discuss that further let's open an issue for that and we might find a good solution together ; )

Finally @leobiscassi complemented:

> In fact, I think this idea is helpful to us if issues will be labeled in [area-label][level] like the example which I give previously, what you think about this?

**Comment by cuducos** [comment]
Ok… sounds good. Let's try.

I think the way the project works (take a look in the first of the [_Four moments_](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#four-moments) for example) will require _Issues without a technical difficult_ (so this will be a kind of open thread to discuss how to implement a solution).

This is not a problem, I'm just trying to ponder on the data we have (yes, there are issues suggesting data collection, but the sources and technology are still open to discussion).

Let's see what kind of labels we need then:

* **Data collection** (`easy`/`medium`/`hard`)
* **Analysis** (`easy`/`medium`/`hard`)
* Maybe **Infrastructure** (`easy`/`medium`/`hard`) for stuff like #80?
* Maybe **Communication** (with no level of difficult) for stuff like #69? 
* Maybe **Documentation** (with no level of difficult) for stuff like updates in install instructions, link to the groups/page/forum, general discussion on `README.md`/`CONTRIBUTING.md`?
* Maybe **Community** or **Meta** (with no level of difficult) for stuff like this own Issue ; )

What do you all think about it?

**Comment by leobiscassi** [comment]
Sounds good for me, @cuducos. I think this will be help people with doubts like in *issue* [#90](https://github.com/datasciencebr/serenata-de-amor/issues/90). It would be good tag issues in development with label WIP (Working In Progress), like you do with pull requests, too. :wink: 

Hope this helps :grin:

**Comment by cuducos** [comment]
Ok… I'm gonna create the labels now, but I can't promise I'm gonna (re)label everything. Feel free to come back here and add a comment suggesting a label/level to any given _Issue_.

**Comment by leobiscassi** [comment]
@cuducos nice! :smile:
