### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by pmargreff** [datasciencebr/serenata-de-amor#95]
Hi guys, how about data visualization, do you already chat about? It could be a good way to show to people who haven't any technical skills or are from different field how the project would save a lot of money. I started develop some charts using D3. I'm curious to know about the kind of features you think is relevant to show (?). At this time I'm trying the money by person, by state and by subquota, what do u think about it?

**Comment by cuducos** [comment]
That's a great topic — thanks @pmargreff! 

I'm aware @filipelinhares was working on something visual, and @vilapedro might be interested in this material for communication purposes.

_Maybe_ this is a topic to be discussed in the [`serenata-website` repo](https://github.com/datasciencebr/serenata-website) in the near future — when we consolidate a structure for a website focused on communication this repo here tends to narrow its focus to data science, while the other one will embrace many communication related topics I guess.

Filipe and Pedro — what do you think?

Pablo would you mind sharing something you already have? Maybe some screenshots would be nice to give more substance to what can be done from it.

**Comment by filipelinhares** [comment]
Hey @pmargreff!

I'm studying data vis and starting to dive in D3 and other tools. As @cuducos said, when we consolidate a structure for the new website we can use visualizations to improves the experience and interaction with the data.

Data visualization is an awesome field to explore in this project :heart:. @pmargreff If you are interested we can schedule a Hangouts to talk more about it :smile:

**Comment by pmargreff** [comment]
We think on three basic kind of visualizations to startup. 

**First**: Compare total values by states monthly, we do that dynamically using [D3 Bar Charts] (http://bl.ocks.org/mbostock/3885304). 

![bycompany](https://cloud.githubusercontent.com/assets/9089847/19821136/9584908a-9d3b-11e6-8629-0b8cded1547b.jpg)

**Second**: A heatmap, to show companies who have received most piece of money, the heatmap show the value, company name, cnpj and ranking position on mouse hover event. We use [Hightcharts heatmap](http://www.highcharts.com/demo/heatmap) because we have found only D3 heatmap using days and months to index the values (calendar heatmaps), maybe in near future we can adapt [this one](https://github.com/DKirwan/calendar-heatmap) to accept a simple matrix and use that. 

![bystate](https://cloud.githubusercontent.com/assets/9089847/19821138/99d87f84-9d3b-11e6-989e-79f2a34edbd9.jpg)

**Third**: A [D3 Radar Chart](http://bl.ocks.org/alandunning/4c36eb1abdb248de34c64f5672afd857) to each congress person. The radar contain 18 axes with subquota categories and the money spent in the each category. Maybe in a second moment we can join 2 or more persons in the same radar to compare ([example here](http://www.visualcinnamon.com/2013/09/making-d3-radar-chart-look-bit-better.html)). We have tried use [this model](http://www.visualcinnamon.com/2015/10/different-look-d3-radar-chart.html), but the problem is, it was build in D3 V3 and it isn't compatible with D3 V4, would be awesome if someone help or refactor this model to version 4, because this Radar looks better in compare with all others. 

After finish an reasonable model and documenting the basic (maybe on the next week) I can open the repo to anyone get it and add new visualizations.

**Comment by pmargreff** [comment]
Another thing, maybe show the values by person in this [tree map](http://mbostock.github.io/d3/talk/20111018/treemap.html), where each color is a sub-quota group and inside we can set the companies and correspondent value in the proportion. What do you think about that?

**Comment by cuducos** [comment]
@pmargreff Those pieces of dataviz are awesome! I think we should fit it somewhere, sure thing. @filipelinhares do you think the new website has an section for that? @vilapedro any thoughts on that?

**Comment by pmargreff** [comment]
Hey, [here is](http://64.137.188.230/#/) (temporary) a first version, you can check the [repo](https://github.com/pmargreff/serenata-de-amor-visualization) with a basic documentation to start up the project. Feel free to suggestions or ideas.

**Comment by pmargreff** [comment]
@cuducos I understand, it could point to the wrong way if u don't have all details, but I don't think it's hard. 

For the first suggestion is possible `divide the state value by the number of congress people` from this state, it will show the mean, and show the number of congress person and total value in the tooltip. 

I'm only a little confuse with the second one, you say the possible total `(number of people by state * max possible value)` or the `sum(all values)/state value`? And the suggestion is about generate a number equalizing this two metrics in the same one or divide in two different views/charts? 

About the `HTTP 503` - it's probably because it isn't a server, in the really is something like by backup computer and it isn't properly prepare to maintain a website stable. I have another problem with the size of `json` from the third view, I thinking how compact or make this file smaller (1.3 MB on this moment), but I haven't any good idea yet.

**Comment by cuducos** [comment]
About the second one, I suggest (it's merely a suggestion, I haven't put a lot of thought on it) dividing:

* the mean of expenses by state (the sum of every expense of a given state divided by the number of congresspeople representing this state)
* by the max allowance for this given state

On a second stage dataviz could show who (within this given state) pushes the mean up or down…

About the `503` it was com camera.gov.br (not on your server). I was trying to link the max allowance by state for you ; )

**Comment by pmargreff** [comment]
Yes, I get it and make some sense, but I don't know if will have some impact if the people don't have an idea from the value itself. Maybe a line or something marking the max limit could representing almost the same. 

I really like about the suggestion to see the outliers. I'll think in something and exec when I have some time. 

I updated to mean value, and it really equalize much better, but some weird things happen' like in the lasts months of year (2014/2015) we can see the value bit the max. I'll try to find why and when it's happen to try explain this point.

Another observation, I was checking the last behavior and the `net_value` value isn't consistent for all occurrences, you can [find the new value easily using Julia](https://github.com/pmargreff/serenata-de-amor-visualization/blob/master/script/groupby.jl#L11).

**Comment by cuducos** [comment]
> Maybe a line or something marking the max limit could representing almost the same.
♥️ 

>  I'll try to find why and when it's happen to try explain this point.

Good. I couldn't spend some time on that today, I'm sorry about it.

> Another observation, I was checking the last behavior and the net_value […]

We're debating this on #85, but we haven't reached a decision yet. Hold on a while longer ; )

**Comment by ronydj** [comment]
Why don't you use tools like kibana for data visualization ?

**Comment by pmargreff** [comment]
@cuducos About the net_value bit the roof, I did found any reason, but I send a request to like you suggest on #85.

@ronydj Hello, I never use that, the only thing I know: the people use that with Elastic Search (and it doesn't mean nothing to me). If you know, you don't care about teach, you have free time, contact me on: pmargreff at gmail dot com.

**UPDATE:** I added two new charts on site, monthly value and average by party(really like this one).

**Comment by cuducos** [comment]
> About the net_value bit the roof, I did found any reason, but I send a request to like you suggest on #85.

👍 Looking forward to check what they're gonna say ; )

> UPDATE: I added two new charts on site, monthly value and average by party(really like this one).

There's a small _typo_ (Montly instead of Mont**h**ly in one of the titles). But overall it's very good ; )

**Comment by kassimorra** [comment]
Hi Guys,
Friend of mine told my about this great project. I got interested on this subject.

Is there anywhere that can I see what you want to show ?

I read this topic but didn't found the storytelling or the analysis that need to be done.


Kassim

**Comment by pmargreff** [comment]
I get a answer about the net_value bit the max value, the complete answer was:

> Senhor Pablo,
> 
> A Câmara dos Deputados agradece seu contato.
> 
> Em atenção ao solicitado, o Departamento de Orçamento, Finanças e Contabilidade (Defin) da Câmara dos Deputados já se pronunciou no seguinte sentido:
> Com relação ao questionamento de que o gasto médio em um determinado mês apresenta valor superior ao da cota mensal disponibilizada ao parlamentar, o [Ato da Mesa n° 43/2009, de 21/05/2009](http://www2.camara.leg.br/legin/int/atomes/2009/atodamesa-43-21-maio-2009-588364-norma-cd-mesa.html), que institui a Cota para o Exercício da Atividade Parlamentar estabelece: 
> 
> “Art. 13. O saldo da cota não utilizado acumula-se ao longo do exercício financeiro, vedada a acumulação de saldo de um exercício para o seguinte.”
> 
> Portanto, caso o parlamentar não tenha utilizado todo o saldo acumulado durante os primeiros meses do ano, poderá utilizá-lo até o final do exercício financeiro.
> 
> Em caso de dúvidas, estamos à disposição.
> 
  

A simple translate to english: 

> In meeting as follow [Ato da Mesa n° 43/2009, de 21/05/2009](http://www2.camara.leg.br/legin/int/atomes/2009/atodamesa-43-21-maio-2009-588364-norma-cd-mesa.html) means if the total value isn't used in a month it will be cumulative to the next months. The value only expires when the finance year ends. 

And the [13th paragraph](http://imagem.camara.gov.br/Imagem/d/pdf/DCD22MAI2009sup.pdf#page=8) say that. I believe it could impact on some other metrics too.

**Comment by cuducos** [comment]
Great, @pmargreff — many thanks for sharing their response.

Welcome @kassimorra. Sorry about not getting back to you sooner.

> Is there anywhere that can I see what you want to show?

We were discussing that these days and probably @vilapedro will be in touch — he's focused on communication and probably you both could better discuss what would be interesting in terms of _dataviz_.

**Comment by cuducos** [comment]
Closing this as dataviz is more relevant at `serenata-website` repo now.
