### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by egrohs** [datasciencebr/serenata-de-amor#99]
I'm Emanuel, a software analist and programmer from this very corrupt Brazil.
I've got a project myself to catalog corrupt parlamentarians, like zapimovies for search home buildings.
Maybe i can help this project somehow, with data tools, or ideias.
Can u explain me more about this initiative?

**Comment by cuducos** [comment]
Hi Emanuel. Welcome, make yourself at home : )

The idea of cataloguing congresspeople sounds awesome for this project, it could help be very handy in the machine learning phase.

Just checking: have you checked our [contribution guide](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md)? It's the `CONTRIBUTING.md` file, also linked in a yellow box when you opened this very issue. We have plenty of information there about the project organization, different ways to contribute, how to set up your development environment and even the link to our tech group on Telegram where you can meet awesome people.

Can you take a look come up with more specific questions so we can improve this guide and be more welcoming for newcomers?

Many thanks,

**Comment by cuducos** [comment]
As I just saw you interacting in our Telegram group, I think I can close this issue, right?
